/*
 Fuse.js v3.3.0 - Lightweight fuzzy-search (http://fusejs.io)

 Copyright (c) 2012-2017 Kirollos Risk (http://kiro.me)
 All Rights Reserved. Apache Software License 2.0

 http://www.apache.org/licenses/LICENSE-2.0
 Hammer.JS - v2.0.7 - 2016-04-22
 http://hammerjs.github.io/

 Copyright (c) 2016 Jorik Tangelder;
 Licensed under the MIT license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,A,z){h!=Array.prototype&&h!=Object.prototype&&(h[A]=z.value)};$jscomp.getGlobal=function(h){return"undefined"!=typeof window&&window===h?h:"undefined"!=typeof global&&null!=global?global:h};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var h=$jscomp.global.Symbol.iterator;h||(h=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[h]&&$jscomp.defineProperty(Array.prototype,h,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(h){var A=0;return $jscomp.iteratorPrototype(function(){return A<h.length?{done:!1,value:h[A++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(h){$jscomp.initSymbolIterator();h={next:h};h[$jscomp.global.Symbol.iterator]=function(){return this};return h};$jscomp.makeIterator=function(h){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var A=h[Symbol.iterator];return A?A.call(h):$jscomp.arrayIterator(h)};$jscomp.arrayFromIterator=function(h){for(var A,z=[];!(A=h.next()).done;)z.push(A.value);return z};$jscomp.arrayFromIterable=function(h){return h instanceof Array?h:$jscomp.arrayFromIterator($jscomp.makeIterator(h))};
$jscomp.iteratorFromArray=function(h,A){$jscomp.initSymbolIterator();h instanceof String&&(h+="");var z=0,q={next:function(){if(z<h.length){var x=z++;return{value:A(x,h[x]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill=function(h,A,z,q){if(A){z=$jscomp.global;h=h.split(".");for(q=0;q<h.length-1;q++){var x=h[q];x in z||(z[x]={});z=z[x]}h=h[h.length-1];q=z[h];A=A(q);A!=q&&null!=A&&$jscomp.defineProperty(z,h,{configurable:!0,writable:!0,value:A})}};$jscomp.polyfill("Array.prototype.keys",function(h){return h?h:function(){return $jscomp.iteratorFromArray(this,function(h){return h})}},"es6","es3");
$jscomp.polyfill("Array.from",function(h){return h?h:function(h,z,q){$jscomp.initSymbolIterator();z=null!=z?z:function(p){return p};var x=[],C=h[Symbol.iterator];if("function"==typeof C)for(h=C.call(h);!(C=h.next()).done;)x.push(z.call(q,C.value));else{C=h.length;for(var p=0;p<C;p++)x.push(z.call(q,h[p]))}return x}},"es6","es3");$jscomp.polyfill("Array.prototype.entries",function(h){return h?h:function(){return $jscomp.iteratorFromArray(this,function(h,z){return[h,z]})}},"es6","es3");
(function(){var h="undefined"===typeof global?self:global;if("function"!==typeof h.require){var A={},z={},q={},x={}.hasOwnProperty,C=/^\.\.?(\/|$)/,p=function(a,c){var f=[];c=(C.test(c)?a+"/"+c:c).split("/");for(var t=0,g=c.length;t<g;t++)a=c[t],".."===a?f.pop():"."!==a&&""!==a&&f.push(a);return f.join("/")},B=function(a){return function(c){c=p(a.split("/").slice(0,-1).join("/"),c);return h.require(c,a)}},n=function(a){return q[a]?n(q[a]):a},m=function(a,c){return n(p(a.split("/").slice(0,-1).join("/"),
c))},v=function(a,t){null==t&&(t="/");var f=n(a);if(x.call(z,f))return z[f].exports;if(x.call(A,f))return a=A[f],t=c&&c.createHot(f),t={id:f,exports:{},hot:t},z[f]=t,a(t.exports,B(f),t),t.exports;throw Error("Cannot find module '"+a+"' from '"+t+"'");};v.alias=function(a,c){q[c]=a};var r=/\.[^.\/]+$/,e=/\/index(\.[^\/]+)?$/;v.register=v.define=function(a,c){if(a&&"object"===typeof a)for(var f in a)x.call(a,f)&&v.register(f,a[f]);else A[a]=c,delete z[a],r.test(a)&&(c=a.replace(r,""),x.call(q,c)&&q[c].replace(r,
"")!==c+"/index"||(q[c]=a)),e.test(a)&&(c=a.replace(e,""),x.call(q,c)||(q[c]=a))};v.list=function(){var a=[],c;for(c in A)x.call(A,c)&&a.push(c);return a};var c=h._hmr&&new h._hmr(m,v,A,z);v._cache=z;v.hmr=c&&c.wrap;v.brunch=!0;h.require=v}})();
(function(){var h="undefined"===typeof window?this:window,A=function(h,q,x){var C={},p=function(B,n){var m;try{return m=h(n+"/node_modules/"+B)}catch(v){if(-1===v.toString().indexOf("Cannot find module"))throw v;if(-1!==n.indexOf("node_modules"))return n=n.split("/"),m=n.lastIndexOf("node_modules"),n=n.slice(0,m).join("/"),p(B,n)}return C};return function(B){B in q&&(B=q[B]);if(B){if("."!==B[0]&&x){var n=p(B,x);if(n!==C)return n}return h(B)}}};require.register("@fdaciuk/ajax/dist/ajax.min.js",function(h,
q,x){q=A(q,{},"@fdaciuk/ajax");(function(){!function(C,p){"function"==typeof define&&define.amd?define("ajax",p):"object"==typeof h?h=x.exports=p():C.ajax=p()}(this,function(){function h(c,a,e,f){var t=["then","catch","always"].reduce(function(a,c){return a[c]=function(g){return a[c]=g,a},a},{}),g=new XMLHttpRequest;a=p(a,e,c);return g.open(c,a,!0),g.withCredentials=f.hasOwnProperty("withCredentials"),B(g,f.headers,e),g.addEventListener("readystatechange",m(t,g),!1),g.send(r(e)?JSON.stringify(e):
e),t.abort=function(){return g.abort()},t}function p(c,a,t){if("get"!==t.toLowerCase()||!a)return c;a=r(a)?e(a):a;t=-1<c.indexOf("?")?"\x26":"?";return c+t+a}function B(c,a,e){a=a||{};n(a)||(a["Content-Type"]=r(e)?"application/json":"application/x-www-form-urlencoded");Object.keys(a).forEach(function(f){a[f]&&c.setRequestHeader(f,a[f])})}function n(c){return Object.keys(c).some(function(a){return"content-type"===a.toLowerCase()})}function m(c,a){return function f(){a.readyState===a.DONE&&(a.removeEventListener("readystatechange",
f,!1),c.always.apply(c,v(a)),200<=a.status&&300>a.status?c.then.apply(c,v(a)):c["catch"].apply(c,v(a)))}}function v(c){try{var a=JSON.parse(c.responseText)}catch(t){a=c.responseText}return[a,c]}function r(c){return"[object Object]"===Object.prototype.toString.call(c)}function e(c,a){return Object.keys(c).map(function(t){if(c.hasOwnProperty(t)&&void 0!==c[t]){var f=c[t];return t=a?a+"["+t+"]":t,null!==f&&"object"==typeof f?e(f,t):encodeURIComponent(t)+"\x3d"+encodeURIComponent(f)}}).filter(Boolean).join("\x26")}
return function(c){var a=["get","post","put","delete"];return c=c||{},c.baseUrl=c.baseUrl||"",c.method&&c.url?h(c.method,c.baseUrl+c.url,c.data||null,c):a.reduce(function(a,f){return a[f]=function(a,g){return h(f,c.baseUrl+a,g||null,c)},a},{})}})})()});require.register("fuse.js/dist/fuse.js",function(h,q,x){q=A(q,{},"fuse.js");(function(){(function(C,p){"object"===typeof h&&"object"===typeof x?x.exports=p():"function"===typeof define&&define.amd?define("Fuse",[],p):"object"===typeof h?h.Fuse=p():
C.Fuse=p()})(this,function(){return function(h){function p(n){if(C[n])return C[n].exports;var m=C[n]={i:n,l:!1,exports:{}};h[n].call(m.exports,m,m.exports,p);m.l=!0;return m.exports}var C={};p.m=h;p.c=C;p.i=function(n){return n};p.d=function(n,m,v){p.o(n,m)||Object.defineProperty(n,m,{configurable:!1,enumerable:!0,get:v})};p.n=function(n){var m=n&&n.__esModule?function(){return n["default"]}:function(){return n};p.d(m,"a",m);return m};p.o=function(n,m){return Object.prototype.hasOwnProperty.call(n,
m)};p.p="";return p(p.s=8)}([function(h,p,B){h.exports=function(n){return Array.isArray?Array.isArray(n):"[object Array]"===Object.prototype.toString.call(n)}},function(h,p,B){var n=function(){function e(c,a){for(var e=0;e<a.length;e++){var f=a[e];f.enumerable=f.enumerable||!1;f.configurable=!0;"value"in f&&(f.writable=!0);Object.defineProperty(c,f.key,f)}}return function(c,a,t){a&&e(c.prototype,a);t&&e(c,t);return c}}(),m=B(5),v=B(7),r=B(4);p=function(){function e(c,a){var t=a.location;t=void 0===
t?0:t;var f=a.distance;f=void 0===f?100:f;var m=a.threshold;m=void 0===m?.6:m;var g=a.maxPatternLength;g=void 0===g?32:g;var k=a.isCaseSensitive;k=void 0===k?!1:k;var w=a.tokenSeparator;w=void 0===w?/ +/g:w;var d=a.findAllMatches;d=void 0===d?!1:d;a=a.minMatchCharLength;a=void 0===a?1:a;if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");this.options={location:t,distance:f,threshold:m,maxPatternLength:g,isCaseSensitive:k,tokenSeparator:w,findAllMatches:d,minMatchCharLength:a};
this.pattern=this.options.isCaseSensitive?c:c.toLowerCase();this.pattern.length<=g&&(this.patternAlphabet=r(this.pattern))}n(e,[{key:"search",value:function(c){this.options.isCaseSensitive||(c=c.toLowerCase());if(this.pattern===c)return{isMatch:!0,score:0,matchedIndices:[[0,c.length-1]]};var a=this.options,e=a.tokenSeparator;if(this.pattern.length>a.maxPatternLength)return m(c,this.pattern,e);a=this.options;return v(c,this.pattern,this.patternAlphabet,{location:a.location,distance:a.distance,threshold:a.threshold,
findAllMatches:a.findAllMatches,minMatchCharLength:a.minMatchCharLength})}}]);return e}();h.exports=p},function(h,p,B){var n=B(0),m=function r(e,c,a){if(c){var t=c.indexOf("."),f=c,m=null;-1!==t&&(f=c.slice(0,t),m=c.slice(t+1));e=e[f];if(null!==e&&void 0!==e)if(m||"string"!==typeof e&&"number"!==typeof e)if(n(e))for(c=0,t=e.length;c<t;c+=1)r(e[c],m,a);else m&&r(e,m,a);else a.push(e.toString())}else a.push(e);return a};h.exports=function(n,e){return m(n,e,[])}},function(h,p,B){h.exports=function(){for(var n=
0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],m=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,p=[],r=-1,e,c=0,a=n.length;c<a;c+=1)(e=n[c])&&-1===r?r=c:e||-1===r||(e=c-1,e-r+1>=m&&p.push([r,e]),r=-1);n[c-1]&&c-r>=m&&p.push([r,c-1]);return p}},function(h,p,B){h.exports=function(n){for(var m={},p=n.length,r=0;r<p;r+=1)m[n.charAt(r)]=0;for(r=0;r<p;r+=1)m[n.charAt(r)]|=1<<p-r-1;return m}},function(h,p,B){var n=/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g;h.exports=function(m,p){var r=2<
arguments.length&&void 0!==arguments[2]?arguments[2]:/ +/g;r=new RegExp(p.replace(n,"\\$\x26").replace(r,"|"));r=m.match(r);var e=!!r,c=[];if(e)for(var a=0,t=r.length;a<t;a+=1){var f=r[a];c.push([m.indexOf(f),f.length-1])}return{score:e?.5:1,isMatch:e,matchedIndices:c}}},function(h,p,B){h.exports=function(n,m){var p=m.errors,r=m.currentLocation,e=m.expectedLocation;m=m.distance;m=void 0===m?100:m;n=(void 0===p?0:p)/n.length;r=Math.abs((void 0===e?0:e)-(void 0===r?0:r));return m?n+r/m:r?1:n}},function(h,
p,B){var n=B(6),m=B(3);h.exports=function(p,h,e,c){var a=c.location,t=c.distance;t=void 0===t?100:t;var f=c.threshold,y=c.findAllMatches;y=void 0===y?!1:y;c=c.minMatchCharLength;c=void 0===c?1:c;a=void 0===a?0:a;var g=p.length;f=void 0===f?.6:f;for(var k=p.indexOf(h,a),w=h.length,d=[],b=0;b<g;b+=1)d[b]=0;-1!==k&&(k=n(h,{errors:0,currentLocation:k,expectedLocation:a,distance:t}),f=Math.min(k,f),k=p.lastIndexOf(h,a+w),-1!==k&&(k=n(h,{errors:0,currentLocation:k,expectedLocation:a,distance:t}),f=Math.min(k,
f)));k=-1;b=[];for(var l=1,H=w+g,E=1<<w-1,I=0;I<w;I+=1){for(var r=0,F=H;r<F;)n(h,{errors:I,currentLocation:a+F,expectedLocation:a,distance:t})<=f?r=F:H=F,F=Math.floor((H-r)/2+r);H=F;r=Math.max(1,a-F+1);var K=y?g:Math.min(a+F,g)+w;F=Array(K+2);for(F[K+1]=(1<<I)-1;K>=r;--K){var L=K-1,G=e[p.charAt(L)];G&&(d[L]=1);F[K]=(F[K+1]<<1|1)&G;0!==I&&(F[K]=F[K]|(b[K+1]|b[K])<<1|1|b[K+1]);if(F[K]&E&&(l=n(h,{errors:I,currentLocation:L,expectedLocation:a,distance:t}),l<=f)){f=l;k=L;if(k<=a)break;r=Math.max(1,2*a-
k)}}if(n(h,{errors:I+1,currentLocation:a,expectedLocation:a,distance:t})>f)break;b=F}return{isMatch:0<=k,score:0===l?.001:l,matchedIndices:m(d,c)}}},function(h,p,B){var n=function(){function e(c,a){for(var e=0;e<a.length;e++){var f=a[e];f.enumerable=f.enumerable||!1;f.configurable=!0;"value"in f&&(f.writable=!0);Object.defineProperty(c,f.key,f)}}return function(c,a,t){a&&e(c.prototype,a);t&&e(c,t);return c}}(),m=B(1),v=B(2),r=B(0);p=function(){function e(c,a){var t=a.location;t=void 0===t?0:t;var f=
a.distance;f=void 0===f?100:f;var m=a.threshold;m=void 0===m?.6:m;var g=a.maxPatternLength;g=void 0===g?32:g;var k=a.caseSensitive;k=void 0===k?!1:k;var w=a.tokenSeparator;w=void 0===w?/ +/g:w;var d=a.findAllMatches;d=void 0===d?!1:d;var b=a.minMatchCharLength;b=void 0===b?1:b;var l=a.id;l=void 0===l?null:l;var H=a.keys;H=void 0===H?[]:H;var E=a.shouldSort;E=void 0===E?!0:E;var I=a.getFn;I=void 0===I?v:I;var n=a.sortFn;n=void 0===n?function(b,a){return b.score-a.score}:n;var F=a.tokenize;F=void 0===
F?!1:F;var p=a.matchAllTokens;p=void 0===p?!1:p;var h=a.includeMatches;h=void 0===h?!1:h;var r=a.includeScore;r=void 0===r?!1:r;a=a.verbose;a=void 0===a?!1:a;if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");this.options={location:t,distance:f,threshold:m,maxPatternLength:g,isCaseSensitive:k,tokenSeparator:w,findAllMatches:d,minMatchCharLength:b,id:l,keys:H,includeMatches:h,includeScore:r,shouldSort:E,getFn:I,sortFn:n,verbose:a,tokenize:F,matchAllTokens:p};this.setCollection(c)}
n(e,[{key:"setCollection",value:function(c){return this.list=c}},{key:"search",value:function(c){this._log('---------\nSearch pattern: "'+c+'"');c=this._prepareSearchers(c);c=this._search(c.tokenSearchers,c.fullSearcher);var a=c.results;this._computeScore(c.weights,a);this.options.shouldSort&&this._sort(a);return this._format(a)}},{key:"_prepareSearchers",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",a=[];if(this.options.tokenize)for(var e=c.split(this.options.tokenSeparator),
f=0,n=e.length;f<n;f+=1)a.push(new m(e[f],this.options));c=new m(c,this.options);return{tokenSearchers:a,fullSearcher:c}}},{key:"_search",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],a=arguments[1],e=this.list,f={},m=[];if("string"===typeof e[0]){for(var g=0,k=e.length;g<k;g+=1)this._analyze({key:"",value:e[g],record:g,index:g},{resultMap:f,results:m,tokenSearchers:c,fullSearcher:a});return{weights:null,results:m}}g={};k=0;for(var w=e.length;k<w;k+=1)for(var d=
e[k],b=0,l=this.options.keys.length;b<l;b+=1){var H=this.options.keys[b];if("string"!==typeof H){g[H.name]={weight:1-H.weight||1};if(0>=H.weight||1<H.weight)throw Error("Key weight has to be \x3e 0 and \x3c\x3d 1");H=H.name}else g[H]={weight:1};this._analyze({key:H,value:this.options.getFn(d,H),record:d,index:k},{resultMap:f,results:m,tokenSearchers:c,fullSearcher:a})}return{weights:g,results:m}}},{key:"_analyze",value:function(c,a){var e=c.key,f=c.arrayIndex,m=void 0===f?-1:f;f=c.value;var g=c.record;
c=c.index;var k=a.tokenSearchers;k=void 0===k?[]:k;var w=a.fullSearcher,d=void 0===w?[]:w;w=a.resultMap;w=void 0===w?{}:w;a=a.results;a=void 0===a?[]:a;if(void 0!==f&&null!==f){var b=!1,l=-1,H=0;if("string"===typeof f){this._log("\nKey: "+(""===e?"-":e));d=d.search(f);this._log('Full text: "'+f+'", score: '+d.score);if(this.options.tokenize){l=f.split(this.options.tokenSeparator);for(var E=[],I=0;I<k.length;I+=1){var n=k[I];this._log('\nPattern: "'+n.pattern+'"');for(var F=!1,p=0;p<l.length;p+=1){var h=
l[p],G=n.search(h),D={};G.isMatch?(D[h]=G.score,F=b=!0,E.push(G.score)):(D[h]=1,this.options.matchAllTokens||E.push(1));this._log('Token: "'+h+'", score: '+D[h])}F&&(H+=1)}l=E[0];I=E.length;for(n=1;n<I;n+=1)l+=E[n];l/=I;this._log("Token score average:",l)}E=d.score;-1<l&&(E=(E+l)/2);this._log("Score average:",E);k=this.options.tokenize&&this.options.matchAllTokens?H>=k.length:!0;this._log("\nCheck Matches: "+k);(b||d.isMatch)&&k&&((k=w[c])?k.output.push({key:e,arrayIndex:m,value:f,score:E,matchedIndices:d.matchedIndices}):
(w[c]={item:g,output:[{key:e,arrayIndex:m,value:f,score:E,matchedIndices:d.matchedIndices}]},a.push(w[c])))}else if(r(f))for(m=0,b=f.length;m<b;m+=1)this._analyze({key:e,arrayIndex:m,value:f[m],record:g,index:c},{resultMap:w,results:a,tokenSearchers:k,fullSearcher:d})}}},{key:"_computeScore",value:function(c,a){this._log("\n\nComputing score:\n");for(var e=0,f=a.length;e<f;e+=1){for(var m=a[e].output,g=m.length,k=1,w=1,d=0;d<g;d+=1){var b=c?c[m[d].key].weight:1,l=(1===b?m[d].score:m[d].score||.001)*
b;1!==b?w=Math.min(w,l):(m[d].nScore=l,k*=l)}a[e].score=1===w?k:w;this._log(a[e])}}},{key:"_sort",value:function(c){this._log("\n\nSorting....");c.sort(this.options.sortFn)}},{key:"_format",value:function(c){var a=[];this.options.verbose&&this._log("\n\nOutput:\n\n",JSON.stringify(c));var e=[];this.options.includeMatches&&e.push(function(b,a){b=b.output;a.matches=[];for(var c=0,l=b.length;c<l;c+=1){var g=b[c];if(0!==g.matchedIndices.length){var d={indices:g.matchedIndices,value:g.value};g.key&&(d.key=
g.key);g.hasOwnProperty("arrayIndex")&&-1<g.arrayIndex&&(d.arrayIndex=g.arrayIndex);a.matches.push(d)}}});this.options.includeScore&&e.push(function(b,a){a.score=b.score});for(var f=0,m=c.length;f<m;f+=1){var g=c[f];this.options.id&&(g.item=this.options.getFn(g.item,this.options.id)[0]);if(e.length){for(var k={item:g.item},w=0,d=e.length;w<d;w+=1)e[w](g,k);a.push(k)}else a.push(g.item)}return a}},{key:"_log",value:function(){if(this.options.verbose){var c;(c=console).log.apply(c,arguments)}}}]);return e}();
h.exports=p}])})})()});require.register("hammerjs/hammer.js",function(h,q,x){q=A(q,{},"hammerjs");(function(){(function(h,p,B,n){function m(b,c,g){return setTimeout(a(b,g),c)}function v(b,a,c){return Array.isArray(b)?(r(b,c[a],c),!0):!1}function r(b,a,c){var u;if(b)if(b.forEach)b.forEach(a,c);else if(b.length!==n)for(u=0;u<b.length;)a.call(c,b[u],u,b),u++;else for(u in b)b.hasOwnProperty(u)&&a.call(c,b[u],u,b)}function e(b,a,c){var u="DEPRECATED METHOD: "+a+"\n"+c+" AT \n";return function(){var a=
Error("get-stack-trace");a=a&&a.stack?a.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@"):"Unknown Stack Trace";var c=h.console&&(h.console.warn||h.console.log);c&&c.call(h.console,u,a);return b.apply(this,arguments)}}function c(b,a,c){a=a.prototype;var u=b.prototype=Object.create(a);u.constructor=b;u._super=a;c&&Q(u,c)}function a(b,a){return function(){return b.apply(a,arguments)}}function t(b,a){return"function"==typeof b?b.apply(a?
a[0]||n:n,a):b}function f(b,a,c){r(k(a),function(u){b.addEventListener(u,c,!1)})}function y(b,a,c){r(k(a),function(u){b.removeEventListener(u,c,!1)})}function g(b,a){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}function k(b){return b.trim().split(/\s+/g)}function w(b,a,c){if(b.indexOf&&!c)return b.indexOf(a);for(var u=0;u<b.length;){if(c&&b[u][c]==a||!c&&b[u]===a)return u;u++}return-1}function d(b){return Array.prototype.slice.call(b,0)}function b(b,a,c){for(var u=[],g=[],l=0;l<b.length;){var d=
a?b[l][a]:b[l];0>w(g,d)&&u.push(b[l]);g[l]=d;l++}c&&(u=a?u.sort(function(b,u){return b[a]>u[a]}):u.sort());return u}function l(b,a){for(var u,c=a[0].toUpperCase()+a.slice(1),g=0;g<ha.length;){u=(u=ha[g])?u+c:a;if(u in b)return u;g++}return n}function H(b){b=b.ownerDocument||b;return b.defaultView||b.parentWindow||h}function E(b,a){var u=this;this.manager=b;this.callback=a;this.element=b.element;this.target=b.options.inputTarget;this.domHandler=function(a){t(b.options.enable,[b])&&u.handler(a)};this.init()}
function I(b){var a=b.options.inputClass;return new (a?a:ta?N:ua?z:ia?Y:q)(b,sa)}function sa(b,a,c){var u=c.pointers.length,l=c.changedPointers.length;var d=a&1&&0===u-l;c.isFirst=!!d;c.isFinal=!!(a&12&&0===u-l);d&&(b.session={});c.eventType=a;a=b.session;u=c.pointers;l=u.length;a.firstInput||(a.firstInput=F(c));1<l&&!a.firstMultiple?a.firstMultiple=F(c):1===l&&(a.firstMultiple=!1);d=a.firstInput;var k=(l=a.firstMultiple)?l.center:d.center;var f=c.center=K(u);c.timeStamp=Z();c.deltaTime=c.timeStamp-
d.timeStamp;c.angle=D(k,f);c.distance=G(k,f);d=c.center;k=a.offsetDelta||{};f=a.prevDelta||{};var E=a.prevInput||{};if(1===c.eventType||4===E.eventType)f=a.prevDelta={x:E.deltaX||0,y:E.deltaY||0},k=a.offsetDelta={x:d.x,y:d.y};c.deltaX=f.x+(d.x-k.x);c.deltaY=f.y+(d.y-k.y);c.offsetDirection=L(c.deltaX,c.deltaY);k=c.deltaTime;d=c.deltaX/k||0;k=c.deltaY/k||0;c.overallVelocityX=d;c.overallVelocityY=k;c.overallVelocity=R(d)>R(k)?d:k;l?(d=l.pointers,d=G(u[0],u[1],T)/G(d[0],d[1],T)):d=1;c.scale=d;l?(l=l.pointers,
u=D(u[1],u[0],T)+D(l[1],l[0],T)):u=0;c.rotation=u;c.maxPointers=a.prevInput?c.pointers.length>a.prevInput.maxPointers?c.pointers.length:a.prevInput.maxPointers:c.pointers.length;k=a.lastInterval||c;u=c.timeStamp-k.timeStamp;8!=c.eventType&&(25<u||k.velocity===n)?(d=c.deltaX-k.deltaX,k=c.deltaY-k.deltaY,f=d/u||0,E=k/u||0,u=f,l=E,f=R(f)>R(E)?f:E,d=L(d,k),a.lastInterval=c):(f=k.velocity,u=k.velocityX,l=k.velocityY,d=k.direction);c.velocity=f;c.velocityX=u;c.velocityY=l;c.direction=d;a=b.element;g(c.srcEvent.target,
a)&&(a=c.srcEvent.target);c.target=a;b.emit("hammer.input",c);b.recognize(c);b.session.prevInput=c}function F(b){for(var a=[],c=0;c<b.pointers.length;)a[c]={clientX:S(b.pointers[c].clientX),clientY:S(b.pointers[c].clientY)},c++;return{timeStamp:Z(),pointers:a,center:K(a),deltaX:b.deltaX,deltaY:b.deltaY}}function K(b){var a=b.length;if(1===a)return{x:S(b[0].clientX),y:S(b[0].clientY)};for(var c=0,u=0,l=0;l<a;)c+=b[l].clientX,u+=b[l].clientY,l++;return{x:S(c/a),y:S(u/a)}}function L(b,a){return b===
a?1:R(b)>=R(a)?0>b?2:4:0>a?8:16}function G(b,a,c){c||(c=ja);var u=a[c[0]]-b[c[0]];b=a[c[1]]-b[c[1]];return Math.sqrt(u*u+b*b)}function D(b,a,c){c||(c=ja);return 180*Math.atan2(a[c[1]]-b[c[1]],a[c[0]]-b[c[0]])/Math.PI}function q(){this.evEl=va;this.evWin=wa;this.pressed=!1;E.apply(this,arguments)}function N(){this.evEl=ka;this.evWin=la;E.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function C(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";
this.started=!1;E.apply(this,arguments)}function z(){this.evTarget=xa;this.targetIds={};E.apply(this,arguments)}function A(a,c){var u=d(a.touches),l=this.targetIds;if(c&3&&1===u.length)return l[u[0].identifier]=!0,[u,u];a=d(a.changedTouches);var k=[],f=this.target;var E=u.filter(function(b){return g(b.target,f)});if(1===c)for(u=0;u<E.length;)l[E[u].identifier]=!0,u++;for(u=0;u<a.length;)l[a[u].identifier]&&k.push(a[u]),c&12&&delete l[a[u].identifier],u++;if(k.length)return[b(E.concat(k),"identifier",
!0),k]}function Y(){E.apply(this,arguments);var b=a(this.handler,this);this.touch=new z(this.manager,b);this.mouse=new q(this.manager,b);this.primaryTouch=null;this.lastTouches=[]}function J(b){b=b.changedPointers[0];if(b.identifier===this.primaryTouch){var a={x:b.clientX,y:b.clientY};this.lastTouches.push(a);var c=this.lastTouches;setTimeout(function(){var b=c.indexOf(a);-1<b&&c.splice(b,1)},2500)}}function aa(b,a){this.manager=b;this.set(a)}function ya(b){if(-1<b.indexOf("none"))return"none";var a=
-1<b.indexOf("pan-x"),c=-1<b.indexOf("pan-y");return a&&c?"none":a||c?a?"pan-x":"pan-y":-1<b.indexOf("manipulation")?"manipulation":"auto"}function O(b){this.options=Q({},this.defaults,b||{});this.id=za++;this.manager=null;b=this.options.enable;this.options.enable=b===n?!0:b;this.state=1;this.simultaneous={};this.requireFail=[]}function ma(b){return b&16?"cancel":b&8?"end":b&4?"move":b&2?"start":""}function na(b){return 16==b?"down":8==b?"up":2==b?"left":4==b?"right":""}function U(b,a){return(a=a.manager)?
a.get(b):b}function M(){O.apply(this,arguments)}function V(){M.apply(this,arguments);this.pY=this.pX=null}function ba(){M.apply(this,arguments)}function ca(){O.apply(this,arguments);this._input=this._timer=null}function da(){M.apply(this,arguments)}function ea(){M.apply(this,arguments)}function W(){O.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function P(b,a){a=a||{};var c=a.recognizers;a.recognizers=c===n?P.defaults.preset:c;return new fa(b,a)}function fa(b,
a){this.options=Q({},P.defaults,a||{});this.options.inputTarget=this.options.inputTarget||b;this.handlers={};this.session={};this.recognizers=[];this.oldCssProps={};this.element=b;this.input=I(this);this.touchAction=new aa(this,this.options.touchAction);oa(this,!0);r(this.options.recognizers,function(b){var a=this.add(new b[0](b[1]));b[2]&&a.recognizeWith(b[2]);b[3]&&a.requireFailure(b[3])},this)}function oa(b,a){var c=b.element;if(c.style){var u;r(b.options.cssProps,function(g,d){u=l(c.style,d);
a?(b.oldCssProps[u]=c.style[u],c.style[u]=g):c.style[u]=b.oldCssProps[u]||""});a||(b.oldCssProps={})}}function Aa(b,a){var c=p.createEvent("Event");c.initEvent(b,!0,!0);c.gesture=a;a.target.dispatchEvent(c)}var ha=" webkit Moz MS ms o".split(" "),Ba=p.createElement("div"),S=Math.round,R=Math.abs,Z=Date.now;var Q="function"!==typeof Object.assign?function(b){if(b===n||null===b)throw new TypeError("Cannot convert undefined or null to object");for(var a=Object(b),c=1;c<arguments.length;c++){var l=arguments[c];
if(l!==n&&null!==l)for(var u in l)l.hasOwnProperty(u)&&(a[u]=l[u])}return a}:Object.assign;var pa=e(function(b,a,c){for(var l=Object.keys(a),u=0;u<l.length;){if(!c||c&&b[l[u]]===n)b[l[u]]=a[l[u]];u++}return b},"extend","Use `assign`."),Ca=e(function(b,a){return pa(b,a,!0)},"merge","Use `assign`."),za=1,Da=/mobile|tablet|ip(ad|hone|od)|android/i,ia="ontouchstart"in h,ta=l(h,"PointerEvent")!==n,ua=ia&&Da.test(navigator.userAgent),ja=["x","y"],T=["clientX","clientY"];E.prototype={handler:function(){},
init:function(){this.evEl&&f(this.element,this.evEl,this.domHandler);this.evTarget&&f(this.target,this.evTarget,this.domHandler);this.evWin&&f(H(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&y(this.element,this.evEl,this.domHandler);this.evTarget&&y(this.target,this.evTarget,this.domHandler);this.evWin&&y(H(this.element),this.evWin,this.domHandler)}};var Ea={mousedown:1,mousemove:2,mouseup:4},va="mousedown",wa="mousemove mouseup";c(q,E,{handler:function(b){var a=Ea[b.type];
a&1&&0===b.button&&(this.pressed=!0);a&2&&1!==b.which&&(a=4);this.pressed&&(a&4&&(this.pressed=!1),this.callback(this.manager,a,{pointers:[b],changedPointers:[b],pointerType:"mouse",srcEvent:b}))}});var Fa={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ga={2:"touch",3:"pen",4:"mouse",5:"kinect"},ka="pointerdown",la="pointermove pointerup pointercancel";h.MSPointerEvent&&!h.PointerEvent&&(ka="MSPointerDown",la="MSPointerMove MSPointerUp MSPointerCancel");c(N,E,{handler:function(b){var a=
this.store,c=!1,l=b.type.toLowerCase().replace("ms","");l=Fa[l];var g=Ga[b.pointerType]||b.pointerType,d="touch"==g,u=w(a,b.pointerId,"pointerId");l&1&&(0===b.button||d)?0>u&&(a.push(b),u=a.length-1):l&12&&(c=!0);0>u||(a[u]=b,this.callback(this.manager,l,{pointers:a,changedPointers:[b],pointerType:g,srcEvent:b}),c&&a.splice(u,1))}});var Ha={touchstart:1,touchmove:2,touchend:4,touchcancel:8};c(C,E,{handler:function(a){var c=Ha[a.type];1===c&&(this.started=!0);if(this.started){var l=d(a.touches);var g=
d(a.changedTouches);c&12&&(l=b(l.concat(g),"identifier",!0));l=[l,g];c&12&&0===l[0].length-l[1].length&&(this.started=!1);this.callback(this.manager,c,{pointers:l[0],changedPointers:l[1],pointerType:"touch",srcEvent:a})}}});var Ia={touchstart:1,touchmove:2,touchend:4,touchcancel:8},xa="touchstart touchmove touchend touchcancel";c(z,E,{handler:function(b){var a=Ia[b.type],c=A.call(this,b,a);c&&this.callback(this.manager,a,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:b})}});c(Y,
E,{handler:function(b,a,c){var l="mouse"==c.pointerType;if(!(l&&c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents)){if("touch"==c.pointerType)a&1?(this.primaryTouch=c.changedPointers[0].identifier,J.call(this,c)):a&12&&J.call(this,c);else{if(l)a:{l=c.srcEvent.clientX;for(var g=c.srcEvent.clientY,d=0;d<this.lastTouches.length;d++){var u=this.lastTouches[d],k=Math.abs(g-u.y);if(25>=Math.abs(l-u.x)&&25>=k){l=!0;break a}}l=!1}if(l)return}this.callback(b,a,c)}},destroy:function(){this.touch.destroy();
this.mouse.destroy()}});var qa=l(Ba.style,"touchAction"),ra=qa!==n,X=function(){if(!ra)return!1;var b={},a=h.CSS&&h.CSS.supports;"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(c){b[c]=a?h.CSS.supports("touch-action",c):!0});return b}();aa.prototype={set:function(b){"compute"==b&&(b=this.compute());ra&&this.manager.element.style&&X[b]&&(this.manager.element.style[qa]=b);this.actions=b.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},
compute:function(){var b=[];r(this.manager.recognizers,function(a){t(a.options.enable,[a])&&(b=b.concat(a.getTouchAction()))});return ya(b.join(" "))},preventDefaults:function(b){var a=b.srcEvent,c=b.offsetDirection;if(this.manager.session.prevented)a.preventDefault();else{var l=this.actions,g=-1<l.indexOf("none")&&!X.none,d=-1<l.indexOf("pan-y")&&!X["pan-y"];l=-1<l.indexOf("pan-x")&&!X["pan-x"];if(g){var k=2>b.distance,u=250>b.deltaTime;if(1===b.pointers.length&&k&&u)return}if(!l||!d)if(g||d&&c&
6||l&&c&24)return this.preventSrc(a)}},preventSrc:function(b){this.manager.session.prevented=!0;b.preventDefault()}};O.prototype={defaults:{},set:function(b){Q(this.options,b);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(b){if(v(b,"recognizeWith",this))return this;var a=this.simultaneous;b=U(b,this);a[b.id]||(a[b.id]=b,b.recognizeWith(this));return this},dropRecognizeWith:function(b){if(v(b,"dropRecognizeWith",this))return this;b=U(b,this);delete this.simultaneous[b.id];
return this},requireFailure:function(b){if(v(b,"requireFailure",this))return this;var a=this.requireFail;b=U(b,this);-1===w(a,b)&&(a.push(b),b.requireFailure(this));return this},dropRequireFailure:function(b){if(v(b,"dropRequireFailure",this))return this;b=U(b,this);b=w(this.requireFail,b);-1<b&&this.requireFail.splice(b,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(b){return!!this.simultaneous[b.id]},emit:function(b){function a(a){c.manager.emit(a,
b)}var c=this,l=this.state;8>l&&a(c.options.event+ma(l));a(c.options.event);b.additionalEvent&&a(b.additionalEvent);8<=l&&a(c.options.event+ma(l))},tryEmit:function(b){if(this.canEmit())return this.emit(b);this.state=32},canEmit:function(){for(var b=0;b<this.requireFail.length;){if(!(this.requireFail[b].state&33))return!1;b++}return!0},recognize:function(b){b=Q({},b);t(this.options.enable,[this,b])?(this.state&56&&(this.state=1),this.state=this.process(b),this.state&30&&this.tryEmit(b)):(this.reset(),
this.state=32)},process:function(b){},getTouchAction:function(){},reset:function(){}};c(M,O,{defaults:{pointers:1},attrTest:function(b){var a=this.options.pointers;return 0===a||b.pointers.length===a},process:function(b){var a=this.state,c=b.eventType,l=a&6;b=this.attrTest(b);return l&&(c&8||!b)?a|16:l||b?c&4?a|8:a&2?a|4:2:32}});c(V,M,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var b=this.options.direction,a=[];b&6&&a.push("pan-y");b&24&&a.push("pan-x");
return a},directionTest:function(b){var a=this.options,c=!0,l=b.distance,g=b.direction,d=b.deltaX,k=b.deltaY;g&a.direction||(a.direction&6?(g=0===d?1:0>d?2:4,c=d!=this.pX,l=Math.abs(b.deltaX)):(g=0===k?1:0>k?8:16,c=k!=this.pY,l=Math.abs(b.deltaY)));b.direction=g;return c&&l>a.threshold&&g&a.direction},attrTest:function(b){return M.prototype.attrTest.call(this,b)&&(this.state&2||!(this.state&2)&&this.directionTest(b))},emit:function(b){this.pX=b.deltaX;this.pY=b.deltaY;var a=na(b.direction);a&&(b.additionalEvent=
this.options.event+a);this._super.emit.call(this,b)}});c(ba,M,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.scale-1)>this.options.threshold||this.state&2)},emit:function(b){1!==b.scale&&(b.additionalEvent=this.options.event+(1>b.scale?"in":"out"));this._super.emit.call(this,b)}});c(ca,O,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},
process:function(b){var a=this.options,c=b.pointers.length===a.pointers,l=b.distance<a.threshold,g=b.deltaTime>a.time;this._input=b;if(!l||!c||b.eventType&12&&!g)this.reset();else if(b.eventType&1)this.reset(),this._timer=m(function(){this.state=8;this.tryEmit()},a.time,this);else if(b.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},emit:function(b){8===this.state&&(b&&b.eventType&4?this.manager.emit(this.options.event+"up",b):(this._input.timeStamp=Z(),this.manager.emit(this.options.event,
this._input)))}});c(da,M,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.rotation)>this.options.threshold||this.state&2)}});c(ea,M,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return V.prototype.getTouchAction.call(this)},attrTest:function(b){var a=this.options.direction;if(a&30)var c=b.overallVelocity;else a&6?c=b.overallVelocityX:
a&24&&(c=b.overallVelocityY);return this._super.attrTest.call(this,b)&&a&b.offsetDirection&&b.distance>this.options.threshold&&b.maxPointers==this.options.pointers&&R(c)>this.options.velocity&&b.eventType&4},emit:function(b){var a=na(b.offsetDirection);a&&this.manager.emit(this.options.event+a,b);this.manager.emit(this.options.event,b)}});c(W,O,{defaults:{event:"tap",pointers:1,taps:1,interval:300,time:250,threshold:9,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(b){var a=
this.options,c=b.pointers.length===a.pointers,l=b.distance<a.threshold,g=b.deltaTime<a.time;this.reset();if(b.eventType&1&&0===this.count)return this.failTimeout();if(l&&g&&c){if(4!=b.eventType)return this.failTimeout();c=this.pTime?b.timeStamp-this.pTime<a.interval:!0;l=!this.pCenter||G(this.pCenter,b.center)<a.posThreshold;this.pTime=b.timeStamp;this.pCenter=b.center;this.count=l&&c?this.count+1:1;this._input=b;if(0===this.count%a.taps)return this.hasRequireFailures()?(this._timer=m(function(){this.state=
8;this.tryEmit()},a.interval,this),2):8}return 32},failTimeout:function(){this._timer=m(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});P.VERSION="2.0.7";P.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,preset:[[da,{enable:!1}],[ba,{enable:!1},["rotate"]],[ea,{direction:6}],[V,{direction:6},
["swipe"]],[W],[W,{event:"doubletap",taps:2},["tap"]],[ca]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};fa.prototype={set:function(b){Q(this.options,b);b.touchAction&&this.touchAction.update();b.inputTarget&&(this.input.destroy(),this.input.target=b.inputTarget,this.input.init());return this},stop:function(b){this.session.stopped=b?2:1},recognize:function(b){var a=this.session;if(!a.stopped){this.touchAction.preventDefaults(b);
var c=this.recognizers,l=a.curRecognizer;if(!l||l&&l.state&8)l=a.curRecognizer=null;for(var g=0;g<c.length;){var d=c[g];2===a.stopped||l&&d!=l&&!d.canRecognizeWith(l)?d.reset():d.recognize(b);!l&&d.state&14&&(l=a.curRecognizer=d);g++}}},get:function(b){if(b instanceof O)return b;for(var a=this.recognizers,c=0;c<a.length;c++)if(a[c].options.event==b)return a[c];return null},add:function(b){if(v(b,"add",this))return this;var a=this.get(b.options.event);a&&this.remove(a);this.recognizers.push(b);b.manager=
this;this.touchAction.update();return b},remove:function(b){if(v(b,"remove",this))return this;if(b=this.get(b)){var a=this.recognizers;b=w(a,b);-1!==b&&(a.splice(b,1),this.touchAction.update())}return this},on:function(b,a){if(b!==n&&a!==n){var c=this.handlers;r(k(b),function(b){c[b]=c[b]||[];c[b].push(a)});return this}},off:function(b,a){if(b!==n){var c=this.handlers;r(k(b),function(b){a?c[b]&&c[b].splice(w(c[b],a),1):delete c[b]});return this}},emit:function(b,a){this.options.domEvents&&Aa(b,a);
var c=this.handlers[b]&&this.handlers[b].slice();if(c&&c.length)for(a.type=b,a.preventDefault=function(){a.srcEvent.preventDefault()},b=0;b<c.length;)c[b](a),b++},destroy:function(){this.element&&oa(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};Q(P,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,
DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:fa,Input:E,TouchAction:aa,TouchInput:z,MouseInput:q,PointerEventInput:N,TouchMouseInput:Y,SingleTouchInput:C,Recognizer:O,AttrRecognizer:M,Tap:W,Pan:V,Swipe:ea,Pinch:ba,Rotate:da,Press:ca,on:f,off:y,each:r,merge:Ca,extend:pa,assign:Q,inherit:c,bindFn:a,prefixed:l});("undefined"!==typeof h?h:"undefined"!==typeof self?self:{}).Hammer=P;"function"===typeof define&&define.amd?define(function(){return P}):
"undefined"!=typeof x&&x.exports?x.exports=P:h[B]=P})(window,document,"Hammer")})()});require.register("marked/lib/marked.js",function(z,q,x){q=A(q,{},"marked");(function(){(function(h){function p(b){this.tokens=[];this.tokens.links={};this.options=b||y.defaults;this.rules=g.normal;this.options.gfm&&(this.rules=this.options.tables?g.tables:g.gfm)}function q(b,a){this.options=a||y.defaults;this.links=b;this.rules=k.normal;this.renderer=this.options.renderer||new n;this.renderer.options=this.options;
if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?k.breaks:k.gfm:this.options.pedantic&&(this.rules=k.pedantic)}function n(b){this.options=b||{}}function m(){}function v(b){this.tokens=[];this.token=null;this.options=b||y.defaults;this.options.renderer=this.options.renderer||new n;this.renderer=this.options.renderer;this.renderer.options=this.options}function r(b,a){return b.replace(a?/&/g:/&(?!#?\w+;)/g,"\x26amp;").replace(/</g,
"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;")}function e(b){return b.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/ig,function(b,a){a=a.toLowerCase();return"colon"===a?":":"#"===a.charAt(0)?"x"===a.charAt(1)?String.fromCharCode(parseInt(a.substring(2),16)):String.fromCharCode(+a.substring(1)):""})}function c(b,a){b=b.source;a=a||"";return{replace:function(a,c){c=c.source||c;c=c.replace(/(^|[^\[])\^/g,"$1");b=b.replace(a,c);return this},getRegex:function(){return new RegExp(b,
a)}}}function a(b,a){w[" "+b]||(/^[^:]+:\/*[^/]*$/.test(b)?w[" "+b]=b+"/":w[" "+b]=b.replace(/[^/]*$/,""));b=w[" "+b];return"//"===a.slice(0,2)?b.replace(/:[\s\S]*/,":")+a:"/"===a.charAt(0)?b.replace(/(:\/*[^/]*)[\s\S]*/,"$1")+a:b+a}function t(){}function f(b){for(var a=1,c,g;a<arguments.length;a++)for(g in c=arguments[a],c)Object.prototype.hasOwnProperty.call(c,g)&&(b[g]=c[g]);return b}function y(b,a,c){if("undefined"===typeof b||null===b)throw Error("marked(): input parameter is undefined or null");
if("string"!==typeof b)throw Error("marked(): input parameter is of type "+Object.prototype.toString.call(b)+", string expected");if(c||"function"===typeof a){c||(c=a,a=null);a=f({},y.defaults,a||{});var l=a.highlight,g=0;try{var d=p.lex(b,a)}catch(L){return c(L)}var k=d.length;var e=function(b){if(b)return a.highlight=l,c(b);try{var g=v.parse(d,a)}catch(D){b=D}a.highlight=l;return b?c(b):c(null,g)};if(!l||3>l.length)return e();delete a.highlight;if(!k)return e();for(;g<d.length;g++)(function(b){return"code"!==
b.type?--k||e():l(b.text,b.lang,function(a,c){if(a)return e(a);if(null==c||c===b.text)return--k||e();b.text=c;b.escaped=!0;--k||e()})})(d[g])}else try{return a&&(a=f({},y.defaults,a)),v.parse(p.lex(b,a),a)}catch(L){L.message+="\nPlease report this to https://github.com/markedjs/marked.";if((a||y.defaults).silent)return"\x3cp\x3eAn error occurred:\x3c/p\x3e\x3cpre\x3e"+r(L.message+"",!0)+"\x3c/pre\x3e";throw L;}}var g={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:t,hr:/^ {0,3}((?:- *){3,}|(?:_ *){3,}|(?:\* *){3,})(?:\n+|$)/,
heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:t,blockquote:/^( {0,3}> ?(paragraph|[^\n]*)(?:\n|$))+/,list:/^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,html:/^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,def:/^ {0,3}\[(label)\]: *\n? *<?([^\s>]+)>?(?:(?: +\n? *| *\n *)(title))? *(?:\n+|$)/,table:t,lheading:/^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,paragraph:/^([^\n]+(?:\n?(?!hr|heading|lheading| {0,3}>|tag)[^\n]+)+)/,text:/^[^\n]+/,_label:/(?:\\[\[\]]|[^\[\]])+/,
_title:/(?:"(?:\\"|[^"]|"[^"\n]*")*"|'\n?(?:[^'\n]+\n?)*'|\([^()]*\))/};g.def=c(g.def).replace("label",g._label).replace("title",g._title).getRegex();g.bullet=/(?:[*+-]|\d+\.)/;g.item=/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/;g.item=c(g.item,"gm").replace(/bull/g,g.bullet).getRegex();g.list=c(g.list).replace(/bull/g,g.bullet).replace("hr","\\n+(?\x3d\\1?(?:(?:- *){3,}|(?:_ *){3,}|(?:\\* *){3,})(?:\\n+|$))").replace("def","\\n+(?\x3d"+g.def.source+")").getRegex();g._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:|[^\\w\\s@]*@)\\b";
g.html=c(g.html).replace("comment",/\x3c!--[\s\S]*?--\x3e/).replace("closed",/<(tag)[\s\S]+?<\/\1>/).replace("closing",/<tag(?:"[^"]*"|'[^']*'|\s[^'"\/>\s]*)*?\/?>/).replace(/tag/g,g._tag).getRegex();g.paragraph=c(g.paragraph).replace("hr",g.hr).replace("heading",g.heading).replace("lheading",g.lheading).replace("tag","\x3c"+g._tag).getRegex();g.blockquote=c(g.blockquote).replace("paragraph",g.paragraph).getRegex();g.normal=f({},g);g.gfm=f({},g.normal,{fences:/^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\n? *\1 *(?:\n+|$)/,
paragraph:/^/,heading:/^ *(#{1,6}) +([^\n]+?) *#* *(?:\n+|$)/});g.gfm.paragraph=c(g.paragraph).replace("(?!","(?!"+g.gfm.fences.source.replace("\\1","\\2")+"|"+g.list.source.replace("\\1","\\3")+"|").getRegex();g.tables=f({},g.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});p.rules=g;p.lex=function(b,a){return(new p(a)).lex(b)};p.prototype.lex=function(b){b=b.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g,
" ").replace(/\u2424/g,"\n");return this.token(b,!0)};p.prototype.token=function(b,a){b=b.replace(/^ +$/gm,"");for(var c,l,d,k,f,e,w;b;){if(d=this.rules.newline.exec(b))b=b.substring(d[0].length),1<d[0].length&&this.tokens.push({type:"space"});if(d=this.rules.code.exec(b))b=b.substring(d[0].length),d=d[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",text:this.options.pedantic?d:d.replace(/\n+$/,"")});else if(d=this.rules.fences.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"code",
lang:d[2],text:d[3]||""});else if(d=this.rules.heading.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"heading",depth:d[1].length,text:d[2]});else if(a&&(d=this.rules.nptable.exec(b))){b=b.substring(d[0].length);f={type:"table",header:d[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:d[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:d[3].replace(/\n$/,"").split("\n")};for(e=0;e<f.align.length;e++)/^ *-+: *$/.test(f.align[e])?f.align[e]="right":/^ *:-+: *$/.test(f.align[e])?f.align[e]=
"center":/^ *:-+ *$/.test(f.align[e])?f.align[e]="left":f.align[e]=null;for(e=0;e<f.cells.length;e++)f.cells[e]=f.cells[e].split(/ *\| */);this.tokens.push(f)}else if(d=this.rules.hr.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"hr"});else if(d=this.rules.blockquote.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"blockquote_start"}),d=d[0].replace(/^ *> ?/gm,""),this.token(d,a),this.tokens.push({type:"blockquote_end"});else if(d=this.rules.list.exec(b)){b=b.substring(d[0].length);
k=d[2];c=1<k.length;this.tokens.push({type:"list_start",ordered:c,start:c?+k:""});d=d[0].match(this.rules.item);c=!1;w=d.length;for(e=0;e<w;e++)f=d[e],l=f.length,f=f.replace(/^ *([*+-]|\d+\.) +/,""),~f.indexOf("\n ")&&(l-=f.length,f=this.options.pedantic?f.replace(/^ {1,4}/gm,""):f.replace(new RegExp("^ {1,"+l+"}","gm"),"")),this.options.smartLists&&e!==w-1&&(l=g.bullet.exec(d[e+1])[0],k===l||1<k.length&&1<l.length||(b=d.slice(e+1).join("\n")+b,e=w-1)),l=c||/\n\n(?!\s*$)/.test(f),e!==w-1&&(c="\n"===
f.charAt(f.length-1),l||(l=c)),this.tokens.push({type:l?"loose_item_start":"list_item_start"}),this.token(f,!1),this.tokens.push({type:"list_item_end"});this.tokens.push({type:"list_end"})}else if(d=this.rules.html.exec(b))b=b.substring(d[0].length),this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:!this.options.sanitizer&&("pre"===d[1]||"script"===d[1]||"style"===d[1]),text:d[0]});else if(a&&(d=this.rules.def.exec(b)))b=b.substring(d[0].length),d[3]&&(d[3]=d[3].substring(1,d[3].length-
1)),k=d[1].toLowerCase(),this.tokens.links[k]||(this.tokens.links[k]={href:d[2],title:d[3]});else if(a&&(d=this.rules.table.exec(b))){b=b.substring(d[0].length);f={type:"table",header:d[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:d[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:d[3].replace(/(?: *\| *)?\n$/,"").split("\n")};for(e=0;e<f.align.length;e++)/^ *-+: *$/.test(f.align[e])?f.align[e]="right":/^ *:-+: *$/.test(f.align[e])?f.align[e]="center":/^ *:-+ *$/.test(f.align[e])?f.align[e]=
"left":f.align[e]=null;for(e=0;e<f.cells.length;e++)f.cells[e]=f.cells[e].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(f)}else if(d=this.rules.lheading.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"heading",depth:"\x3d"===d[2]?1:2,text:d[1]});else if(a&&(d=this.rules.paragraph.exec(b)))b=b.substring(d[0].length),this.tokens.push({type:"paragraph",text:"\n"===d[1].charAt(d[1].length-1)?d[1].slice(0,-1):d[1]});else if(d=this.rules.text.exec(b))b=b.substring(d[0].length),
this.tokens.push({type:"text",text:d[0]});else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));}return this.tokens};var k={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<(scheme:[^\s\x00-\x1f<>]*|email)>/,url:t,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?[a-zA-Z0-9\-]+(?:"[^"]*"|'[^']*'|\s[^<'">\/\s]*)*?\/?>/,link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,em:/^_([^\s_](?:[^_]|__)+?[^\s_])_\b|^\*((?:\*\*|[^*])+?)\*(?!\*)/,
code:/^(`+)\s*([\s\S]*?[^`]?)\s*\1(?!`)/,br:/^ {2,}\n(?!\s*$)/,del:t,text:/^[\s\S]+?(?=[\\<!\[`*]|\b_| {2,}\n|$)/,_scheme:/[a-zA-Z][a-zA-Z0-9+.-]{1,31}/,_email:/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+(@)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_])/};k.autolink=c(k.autolink).replace("scheme",k._scheme).replace("email",k._email).getRegex();k._inside=/(?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]]|\](?=[^\[]*\]))*/;k._href=/\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/;
k.link=c(k.link).replace("inside",k._inside).replace("href",k._href).getRegex();k.reflink=c(k.reflink).replace("inside",k._inside).getRegex();k.normal=f({},k);k.pedantic=f({},k.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});k.gfm=f({},k.normal,{escape:c(k.escape).replace("])","~|])").getRegex(),url:c(/^((?:ftp|https?):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^email/).replace("email",k._email).getRegex(),
_backpedal:/(?:[^?!.,:;*_~()&]+|\([^)]*\)|&(?![a-zA-Z0-9]+;$)|[?!.,:;*_~)]+(?!$))+/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:c(k.text).replace("]|","~]|").replace("|","|https?://|ftp://|www\\.|[a-zA-Z0-9.!#$%\x26'*+/\x3d?^_`{\\|}~-]+@|").getRegex()});k.breaks=f({},k.gfm,{br:c(k.br).replace("{2,}","*").getRegex(),text:c(k.gfm.text).replace("{2,}","*").getRegex()});q.rules=k;q.output=function(b,a,c){return(new q(a,c)).output(b)};q.prototype.output=function(b){for(var a="",c,d;b;)if(d=this.rules.escape.exec(b))b=
b.substring(d[0].length),a+=d[1];else if(d=this.rules.autolink.exec(b))b=b.substring(d[0].length),"@"===d[2]?(c=r(this.mangle(d[1])),d="mailto:"+c):d=c=r(d[1]),a+=this.renderer.link(d,null,c);else if(!this.inLink&&(d=this.rules.url.exec(b)))d[0]=this.rules._backpedal.exec(d[0])[0],b=b.substring(d[0].length),"@"===d[2]?(c=r(d[0]),d="mailto:"+c):(c=r(d[0]),d="www."===d[1]?"http://"+c:c),a+=this.renderer.link(d,null,c);else if(d=this.rules.tag.exec(b))!this.inLink&&/^<a /i.test(d[0])?this.inLink=!0:
this.inLink&&/^<\/a>/i.test(d[0])&&(this.inLink=!1),b=b.substring(d[0].length),a+=this.options.sanitize?this.options.sanitizer?this.options.sanitizer(d[0]):r(d[0]):d[0];else if(d=this.rules.link.exec(b))b=b.substring(d[0].length),this.inLink=!0,a+=this.outputLink(d,{href:d[2],title:d[3]}),this.inLink=!1;else if((d=this.rules.reflink.exec(b))||(d=this.rules.nolink.exec(b)))b=b.substring(d[0].length),c=(d[2]||d[1]).replace(/\s+/g," "),(c=this.links[c.toLowerCase()])&&c.href?(this.inLink=!0,a+=this.outputLink(d,
c),this.inLink=!1):(a+=d[0].charAt(0),b=d[0].substring(1)+b);else if(d=this.rules.strong.exec(b))b=b.substring(d[0].length),a+=this.renderer.strong(this.output(d[2]||d[1]));else if(d=this.rules.em.exec(b))b=b.substring(d[0].length),a+=this.renderer.em(this.output(d[2]||d[1]));else if(d=this.rules.code.exec(b))b=b.substring(d[0].length),a+=this.renderer.codespan(r(d[2].trim(),!0));else if(d=this.rules.br.exec(b))b=b.substring(d[0].length),a+=this.renderer.br();else if(d=this.rules.del.exec(b))b=b.substring(d[0].length),
a+=this.renderer.del(this.output(d[1]));else if(d=this.rules.text.exec(b))b=b.substring(d[0].length),a+=this.renderer.text(r(this.smartypants(d[0])));else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));return a};q.prototype.outputLink=function(b,a){var c=r(a.href);a=a.title?r(a.title):null;return"!"!==b[0].charAt(0)?this.renderer.link(c,a,this.output(b[1])):this.renderer.image(c,a,r(b[1]))};q.prototype.smartypants=function(b){return this.options.smartypants?b.replace(/---/g,"\u2014").replace(/--/g,
"\u2013").replace(/(^|[-\u2014/(\[{"\s])'/g,"$1\u2018").replace(/'/g,"\u2019").replace(/(^|[-\u2014/(\[{\u2018\s])"/g,"$1\u201c").replace(/"/g,"\u201d").replace(/\.{3}/g,"\u2026"):b};q.prototype.mangle=function(b){if(!this.options.mangle)return b;for(var a="",c=b.length,d=0,g;d<c;d++)g=b.charCodeAt(d),.5<Math.random()&&(g="x"+g.toString(16)),a+="\x26#"+g+";";return a};n.prototype.code=function(b,a,c){if(this.options.highlight){var d=this.options.highlight(b,a);null!=d&&d!==b&&(c=!0,b=d)}return a?
'\x3cpre\x3e\x3ccode class\x3d"'+this.options.langPrefix+r(a,!0)+'"\x3e'+(c?b:r(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e\n":"\x3cpre\x3e\x3ccode\x3e"+(c?b:r(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e"};n.prototype.blockquote=function(b){return"\x3cblockquote\x3e\n"+b+"\x3c/blockquote\x3e\n"};n.prototype.html=function(b){return b};n.prototype.heading=function(b,a,c){return"\x3ch"+a+' id\x3d"'+this.options.headerPrefix+c.toLowerCase().replace(/[^\w]+/g,"-")+'"\x3e'+b+"\x3c/h"+a+"\x3e\n"};n.prototype.hr=function(){return this.options.xhtml?
"\x3chr/\x3e\n":"\x3chr\x3e\n"};n.prototype.list=function(b,a,c){var d=a?"ol":"ul";return"\x3c"+d+(a&&1!==c?' start\x3d"'+c+'"':"")+"\x3e\n"+b+"\x3c/"+d+"\x3e\n"};n.prototype.listitem=function(b){return"\x3cli\x3e"+b+"\x3c/li\x3e\n"};n.prototype.paragraph=function(b){return"\x3cp\x3e"+b+"\x3c/p\x3e\n"};n.prototype.table=function(b,a){return"\x3ctable\x3e\n\x3cthead\x3e\n"+b+"\x3c/thead\x3e\n\x3ctbody\x3e\n"+a+"\x3c/tbody\x3e\n\x3c/table\x3e\n"};n.prototype.tablerow=function(b){return"\x3ctr\x3e\n"+
b+"\x3c/tr\x3e\n"};n.prototype.tablecell=function(b,a){var c=a.header?"th":"td";return(a.align?"\x3c"+c+' style\x3d"text-align:'+a.align+'"\x3e':"\x3c"+c+"\x3e")+b+"\x3c/"+c+"\x3e\n"};n.prototype.strong=function(b){return"\x3cstrong\x3e"+b+"\x3c/strong\x3e"};n.prototype.em=function(b){return"\x3cem\x3e"+b+"\x3c/em\x3e"};n.prototype.codespan=function(b){return"\x3ccode\x3e"+b+"\x3c/code\x3e"};n.prototype.br=function(){return this.options.xhtml?"\x3cbr/\x3e":"\x3cbr\x3e"};n.prototype.del=function(b){return"\x3cdel\x3e"+
b+"\x3c/del\x3e"};n.prototype.link=function(b,c,g){if(this.options.sanitize){try{var l=decodeURIComponent(e(b)).replace(/[^\w:]/g,"").toLowerCase()}catch(I){return g}if(0===l.indexOf("javascript:")||0===l.indexOf("vbscript:")||0===l.indexOf("data:"))return g}this.options.baseUrl&&!d.test(b)&&(b=a(this.options.baseUrl,b));b='\x3ca href\x3d"'+b+'"';c&&(b+=' title\x3d"'+c+'"');return b+("\x3e"+g+"\x3c/a\x3e")};n.prototype.image=function(b,c,g){this.options.baseUrl&&!d.test(b)&&(b=a(this.options.baseUrl,
b));b='\x3cimg src\x3d"'+b+'" alt\x3d"'+g+'"';c&&(b+=' title\x3d"'+c+'"');return b+=this.options.xhtml?"/\x3e":"\x3e"};n.prototype.text=function(b){return b};m.prototype.strong=m.prototype.em=m.prototype.codespan=m.prototype.del=m.prototype.text=function(b){return b};m.prototype.link=m.prototype.image=function(b,a,c){return""+c};m.prototype.br=function(){return""};v.parse=function(b,a){return(new v(a)).parse(b)};v.prototype.parse=function(b){this.inline=new q(b.links,this.options);this.inlineText=
new q(b.links,f({},this.options,{renderer:new m}));this.tokens=b.reverse();for(b="";this.next();)b+=this.tok();return b};v.prototype.next=function(){return this.token=this.tokens.pop()};v.prototype.peek=function(){return this.tokens[this.tokens.length-1]||0};v.prototype.parseText=function(){for(var b=this.token.text;"text"===this.peek().type;)b+="\n"+this.next().text;return this.inline.output(b)};v.prototype.tok=function(){switch(this.token.type){case "space":return"";case "hr":return this.renderer.hr();
case "heading":return this.renderer.heading(this.inline.output(this.token.text),this.token.depth,e(this.inlineText.output(this.token.text)));case "code":return this.renderer.code(this.token.text,this.token.lang,this.token.escaped);case "table":var b="";var a="";var c,d;var g="";for(c=0;c<this.token.header.length;c++)g+=this.renderer.tablecell(this.inline.output(this.token.header[c]),{header:!0,align:this.token.align[c]});b+=this.renderer.tablerow(g);for(c=0;c<this.token.cells.length;c++){var k=this.token.cells[c];
g="";for(d=0;d<k.length;d++)g+=this.renderer.tablecell(this.inline.output(k[d]),{header:!1,align:this.token.align[d]});a+=this.renderer.tablerow(g)}return this.renderer.table(b,a);case "blockquote_start":for(a="";"blockquote_end"!==this.next().type;)a+=this.tok();return this.renderer.blockquote(a);case "list_start":a="";b=this.token.ordered;for(c=this.token.start;"list_end"!==this.next().type;)a+=this.tok();return this.renderer.list(a,b,c);case "list_item_start":for(a="";"list_item_end"!==this.next().type;)a+=
"text"===this.token.type?this.parseText():this.tok();return this.renderer.listitem(a);case "loose_item_start":for(a="";"list_item_end"!==this.next().type;)a+=this.tok();return this.renderer.listitem(a);case "html":return a=this.token.pre||this.options.pedantic?this.token.text:this.inline.output(this.token.text),this.renderer.html(a);case "paragraph":return this.renderer.paragraph(this.inline.output(this.token.text));case "text":return this.renderer.paragraph(this.parseText())}};var w={},d=/^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
t.exec=t;y.options=y.setOptions=function(b){f(y.defaults,b);return y};y.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,sanitizer:null,mangle:!0,smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1,headerPrefix:"",renderer:new n,xhtml:!1,baseUrl:null};y.Parser=v;y.parser=v.parse;y.Renderer=n;y.TextRenderer=m;y.Lexer=p;y.lexer=p.lex;y.InlineLexer=q;y.inlineLexer=q.output;y.parse=y;"undefined"!==typeof x&&"object"===typeof z?x.exports=y:"function"===typeof define&&define.amd?
define(function(){return y}):h.marked=y})(this||("undefined"!==typeof window?window:h))})()});require.register("prismjs/prism.js",function(z,q,x){q=A(q,{},"prismjs");(function(){var q="undefined"!==typeof window?window:"undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?self:{},p=function(){var h=/\blang(?:uage)?-([\w-]+)\b/i,n=0,m=q.Prism={manual:q.Prism&&q.Prism.manual,disableWorkerMessageHandler:q.Prism&&q.Prism.disableWorkerMessageHandler,util:{encode:function(e){return e instanceof
p?new p(e.type,m.util.encode(e.content),e.alias):"Array"===m.util.type(e)?e.map(m.util.encode):e.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/\u00a0/g," ")},type:function(e){return Object.prototype.toString.call(e).match(/\[object (\w+)\]/)[1]},objId:function(e){e.__id||Object.defineProperty(e,"__id",{value:++n});return e.__id},clone:function(e,c){var a=m.util.type(e);c=c||{};switch(a){case "Object":if(c[m.util.objId(e)])return c[m.util.objId(e)];var h={};c[m.util.objId(e)]=h;for(var f in e)e.hasOwnProperty(f)&&
(h[f]=m.util.clone(e[f],c));return h;case "Array":if(c[m.util.objId(e)])return c[m.util.objId(e)];h=[];c[m.util.objId(e)]=h;e.forEach(function(a,g){h[g]=m.util.clone(a,c)});return h}return e}},languages:{extend:function(e,c){e=m.util.clone(m.languages[e]);for(var a in c)e[a]=c[a];return e},insertBefore:function(e,c,a,h){h=h||m.languages;var f=h[e];if(2==arguments.length){a=arguments[1];for(var n in a)a.hasOwnProperty(n)&&(f[n]=a[n]);return f}var g={},k;for(k in f)if(f.hasOwnProperty(k)){if(k==c)for(n in a)a.hasOwnProperty(n)&&
(g[n]=a[n]);g[k]=f[k]}m.languages.DFS(m.languages,function(a,c){c===h[e]&&a!=e&&(this[a]=g)});return h[e]=g},DFS:function(e,c,a,h){h=h||{};for(var f in e)e.hasOwnProperty(f)&&((c.call(e,f,e[f],a||f),"Object"!==m.util.type(e[f])||h[m.util.objId(e[f])])?"Array"!==m.util.type(e[f])||h[m.util.objId(e[f])]||(h[m.util.objId(e[f])]=!0,m.languages.DFS(e[f],c,f,h)):(h[m.util.objId(e[f])]=!0,m.languages.DFS(e[f],c,null,h)))}},plugins:{},highlightAll:function(e,c){m.highlightAllUnder(document,e,c)},highlightAllUnder:function(e,
c,a){a={callback:a,selector:'code[class*\x3d"language-"], [class*\x3d"language-"] code, code[class*\x3d"lang-"], [class*\x3d"lang-"] code'};m.hooks.run("before-highlightall",a);e=a.elements||e.querySelectorAll(a.selector);for(var h=0,f;f=e[h++];)m.highlightElement(f,!0===c,a.callback)},highlightElement:function(e,c,a){for(var n,f,p=e;p&&!h.test(p.className);)p=p.parentNode;p&&(n=(p.className.match(h)||[,""])[1].toLowerCase(),f=m.languages[n]);e.className=e.className.replace(h,"").replace(/\s+/g," ")+
" language-"+n;e.parentNode&&(p=e.parentNode,/pre/i.test(p.nodeName)&&(p.className=p.className.replace(h,"").replace(/\s+/g," ")+" language-"+n));var g={element:e,language:n,grammar:f,code:e.textContent};m.hooks.run("before-sanity-check",g);g.code&&g.grammar?(m.hooks.run("before-highlight",g),c&&q.Worker?(e=new Worker(m.filename),e.onmessage=function(c){g.highlightedCode=c.data;m.hooks.run("before-insert",g);g.element.innerHTML=g.highlightedCode;a&&a.call(g.element);m.hooks.run("after-highlight",
g);m.hooks.run("complete",g)},e.postMessage(JSON.stringify({language:g.language,code:g.code,immediateClose:!0}))):(g.highlightedCode=m.highlight(g.code,g.grammar,g.language),m.hooks.run("before-insert",g),g.element.innerHTML=g.highlightedCode,a&&a.call(e),m.hooks.run("after-highlight",g),m.hooks.run("complete",g))):(g.code&&(m.hooks.run("before-highlight",g),g.element.textContent=g.code,m.hooks.run("after-highlight",g)),m.hooks.run("complete",g))},highlight:function(e,c,a){e={code:e,grammar:c,language:a};
m.hooks.run("before-tokenize",e);e.tokens=m.tokenize(e.code,e.grammar);m.hooks.run("after-tokenize",e);return p.stringify(m.util.encode(e.tokens),e.language)},matchGrammar:function(e,c,a,h,f,n,g){var k=m.Token,w;for(w in a)if(a.hasOwnProperty(w)&&a[w]){if(w==g)break;var d=a[w];d="Array"===m.util.type(d)?d:[d];for(var b=0;b<d.length;++b){var l=d[b],p=l.inside,E=!!l.lookbehind,t=!!l.greedy,r=0,F=l.alias;if(t&&!l.pattern.global){var q=l.pattern.toString().match(/[imuy]*$/)[0];l.pattern=RegExp(l.pattern.source,
q+"g")}l=l.pattern||l;q=h;for(var y=f;q<c.length;y+=c[q].length,++q){var G=c[q];if(c.length>e.length)return;if(!(G instanceof k)){if(t&&q!=c.length-1){l.lastIndex=y;var D=l.exec(e);if(!D)break;var v=D.index+(E?D[1].length:0);var N=D.index+D[0].length;var z=q;G=y;for(var B=c.length;z<B&&(G<N||!c[z].type&&!c[z-1].greedy);++z)G+=c[z].length,v>=G&&(++q,y=G);if(c[q]instanceof k)continue;z-=q;G=e.slice(y,G);D.index-=y}else l.lastIndex=0,D=l.exec(G),z=1;D&&(E&&(r=D[1]?D[1].length:0),v=D.index+r,D=D[0].slice(r),
N=v+D.length,v=G.slice(0,v),N=G.slice(N),G=[q,z],v&&(++q,y+=v.length,G.push(v)),D=new k(w,p?m.tokenize(D,p):D,F,D,t),G.push(D),N&&G.push(N),Array.prototype.splice.apply(c,G),1!=z&&m.matchGrammar(e,c,a,q,y,!0,w));if(n)break}}}}},tokenize:function(e,c,a){a=[e];var h=c.rest;if(h){for(var f in h)c[f]=h[f];delete c.rest}m.matchGrammar(e,a,c,0,0,!1);return a},hooks:{all:{},add:function(e,c){var a=m.hooks.all;a[e]=a[e]||[];a[e].push(c)},run:function(e,c){if((e=m.hooks.all[e])&&e.length)for(var a=0,h;h=e[a++];)h(c)}}},
p=m.Token=function(e,c,a,m,f){this.type=e;this.content=c;this.alias=a;this.length=(m||"").length|0;this.greedy=!!f};p.stringify=function(e,c,a){if("string"==typeof e)return e;if("Array"===m.util.type(e))return e.map(function(a){return p.stringify(a,c,e)}).join("");var h={type:e.type,content:p.stringify(e.content,c,a),tag:"span",classes:["token",e.type],attributes:{},language:c,parent:a};e.alias&&(a="Array"===m.util.type(e.alias)?e.alias:[e.alias],Array.prototype.push.apply(h.classes,a));m.hooks.run("wrap",
h);a=Object.keys(h.attributes).map(function(a){return a+'\x3d"'+(h.attributes[a]||"").replace(/"/g,"\x26quot;")+'"'}).join(" ");return"\x3c"+h.tag+' class\x3d"'+h.classes.join(" ")+'"'+(a?" "+a:"")+"\x3e"+h.content+"\x3c/"+h.tag+"\x3e"};if(!q.document){if(!q.addEventListener)return q.Prism;m.disableWorkerMessageHandler||q.addEventListener("message",function(e){e=JSON.parse(e.data);var c=e.language,a=e.immediateClose;q.postMessage(m.highlight(e.code,m.languages[c],c));a&&q.close()},!1);return q.Prism}var r=
document.currentScript||[].slice.call(document.getElementsByTagName("script")).pop();r&&(m.filename=r.src,m.manual||r.hasAttribute("data-manual")||("loading"!==document.readyState?window.requestAnimationFrame?window.requestAnimationFrame(m.highlightAll):window.setTimeout(m.highlightAll,16):document.addEventListener("DOMContentLoaded",m.highlightAll)));return q.Prism}();"undefined"!==typeof x&&x.exports&&(x.exports=p);"undefined"!==typeof h&&(h.Prism=p);p.languages.markup={comment:/\x3c!--[\s\S]*?--\x3e/,
prolog:/<\?[\s\S]+?\?>/,doctype:/<!DOCTYPE[\s\S]+?>/i,cdata:/<!\[CDATA\[[\s\S]*?]]\x3e/i,tag:{pattern:/<\/?(?!\d)[^\s>\/=$<%]+(?:\s+[^\s>\/=]+(?:=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+))?)*\s*\/?>/i,greedy:!0,inside:{tag:{pattern:/^<\/?[^\s>\/]+/i,inside:{punctuation:/^<\/?/,namespace:/^[^\s>\/:]+:/}},"attr-value":{pattern:/=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+)/i,inside:{punctuation:[/^=/,{pattern:/(^|[^\\])["']/,lookbehind:!0}]}},punctuation:/\/?>/,"attr-name":{pattern:/[^\s>\/]+/,
inside:{namespace:/^[^\s>\/:]+:/}}}},entity:/&#?[\da-z]{1,8};/i};p.languages.markup.tag.inside["attr-value"].inside.entity=p.languages.markup.entity;p.hooks.add("wrap",function(h){"entity"===h.type&&(h.attributes.title=h.content.replace(/&amp;/,"\x26"))});p.languages.xml=p.languages.markup;p.languages.html=p.languages.markup;p.languages.mathml=p.languages.markup;p.languages.svg=p.languages.markup;p.languages.css={comment:/\/\*[\s\S]*?\*\//,atrule:{pattern:/@[\w-]+?.*?(?:;|(?=\s*\{))/i,inside:{rule:/@[\w-]+/}},
url:/url\((?:(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1|.*?)\)/i,selector:/[^{}\s][^{};]*?(?=\s*\{)/,string:{pattern:/("|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},property:/[-_a-z\xA0-\uFFFF][-\w\xA0-\uFFFF]*(?=\s*:)/i,important:/\B!important\b/i,"function":/[-a-z0-9]+(?=\()/i,punctuation:/[(){};:]/};p.languages.css.atrule.inside.rest=p.languages.css;p.languages.markup&&(p.languages.insertBefore("markup","tag",{style:{pattern:/(<style[\s\S]*?>)[\s\S]*?(?=<\/style>)/i,lookbehind:!0,
inside:p.languages.css,alias:"language-css",greedy:!0}}),p.languages.insertBefore("inside","attr-value",{"style-attr":{pattern:/\s*style=("|')(?:\\[\s\S]|(?!\1)[^\\])*\1/i,inside:{"attr-name":{pattern:/^\s*style/i,inside:p.languages.markup.tag.inside},punctuation:/^\s*=\s*['"]|['"]\s*$/,"attr-value":{pattern:/.+/i,inside:p.languages.css}},alias:"language-css"}},p.languages.markup.tag));p.languages.clike={comment:[{pattern:/(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)/,lookbehind:!0},{pattern:/(^|[^\\:])\/\/.*/,
lookbehind:!0,greedy:!0}],string:{pattern:/(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},"class-name":{pattern:/((?:\b(?:class|interface|extends|implements|trait|instanceof|new)\s+)|(?:catch\s+\())[\w.\\]+/i,lookbehind:!0,inside:{punctuation:/[.\\]/}},keyword:/\b(?:if|else|while|do|for|return|in|instanceof|function|new|try|throw|catch|finally|null|break|continue)\b/,"boolean":/\b(?:true|false)\b/,"function":/[a-z0-9_]+(?=\()/i,number:/\b0x[\da-f]+\b|(?:\b\d+\.?\d*|\B\.\d+)(?:e[+-]?\d+)?/i,
operator:/--?|\+\+?|!=?=?|<=?|>=?|==?=?|&&?|\|\|?|\?|\*|\/|~|\^|%/,punctuation:/[{}[\];(),.:]/};p.languages.javascript=p.languages.extend("clike",{keyword:/\b(?:as|async|await|break|case|catch|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally|for|from|function|get|if|implements|import|in|instanceof|interface|let|new|null|of|package|private|protected|public|return|set|static|super|switch|this|throw|try|typeof|var|void|while|with|yield)\b/,number:/\b(?:0[xX][\dA-Fa-f]+|0[bB][01]+|0[oO][0-7]+|NaN|Infinity)\b|(?:\b\d+\.?\d*|\B\.\d+)(?:[Ee][+-]?\d+)?/,
"function":/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*\()/i,operator:/-[-=]?|\+[+=]?|!=?=?|<<?=?|>>?>?=?|=(?:==?|>)?|&[&=]?|\|[|=]?|\*\*?=?|\/=?|~|\^=?|%=?|\?|\.{3}/});p.languages.insertBefore("javascript","keyword",{regex:{pattern:/((?:^|[^$\w\xA0-\uFFFF."'\])\s])\s*)\/(\[[^\]\r\n]+]|\\.|[^/\\\[\r\n])+\/[gimyu]{0,5}(?=\s*($|[\r\n,.;})\]]))/,lookbehind:!0,greedy:!0},"function-variable":{pattern:/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*=\s*(?:function\b|(?:\([^()]*\)|[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*)\s*=>))/i,
alias:"function"},constant:/\b[A-Z][A-Z\d_]*\b/});p.languages.insertBefore("javascript","string",{"template-string":{pattern:/`(?:\\[\s\S]|\${[^}]+}|[^\\`])*`/,greedy:!0,inside:{interpolation:{pattern:/\${[^}]+}/,inside:{"interpolation-punctuation":{pattern:/^\${|}$/,alias:"punctuation"},rest:null}},string:/[\s\S]+/}}});p.languages.javascript["template-string"].inside.interpolation.inside.rest=p.languages.javascript;p.languages.markup&&p.languages.insertBefore("markup","tag",{script:{pattern:/(<script[\s\S]*?>)[\s\S]*?(?=<\/script>)/i,
lookbehind:!0,inside:p.languages.javascript,alias:"language-javascript",greedy:!0}});p.languages.js=p.languages.javascript;(function(){"undefined"!==typeof self&&self.Prism&&self.document&&document.querySelector&&(self.Prism.fileHighlight=function(){var h={js:"javascript",py:"python",rb:"ruby",ps1:"powershell",psm1:"powershell",sh:"bash",bat:"batch",h:"c",tex:"latex"};Array.prototype.slice.call(document.querySelectorAll("pre[data-src]")).forEach(function(n){for(var m=n.getAttribute("data-src"),q,
r=n,e=/\blang(?:uage)?-([\w-]+)\b/i;r&&!e.test(r.className);)r=r.parentNode;r&&(q=(n.className.match(e)||[,""])[1]);q||(q=(m.match(/\.(\w+)$/)||[,""])[1],q=h[q]||q);var c=document.createElement("code");c.className="language-"+q;n.textContent="";c.textContent="Loading\u2026";n.appendChild(c);var a=new XMLHttpRequest;a.open("GET",m,!0);a.onreadystatechange=function(){4==a.readyState&&(400>a.status&&a.responseText?(c.textContent=a.responseText,p.highlightElement(c)):c.textContent=400<=a.status?"\u2716 Error "+
a.status+" while fetching file: "+a.statusText:"\u2716 Error: File does not exist or is empty")};a.send(null)});p.plugins.toolbar&&p.plugins.toolbar.registerButton("download-file",function(h){if((h=h.element.parentNode)&&/pre/i.test(h.nodeName)&&h.hasAttribute("data-src")&&h.hasAttribute("data-download-link")){var m=h.getAttribute("data-src"),n=document.createElement("a");n.textContent=h.getAttribute("data-download-link-label")||"Download";n.setAttribute("download","");n.href=m;return n}})},document.addEventListener("DOMContentLoaded",
self.Prism.fileHighlight))})()})()});require.register("components/main.component.svelte",function(h,q,x){function z(g,k){var f,d,b,l,e,h,m,n,p,q,r=new a({root:g.root});r.on("mobilemenu",function(b){g.handleMobileMenu(b)});r.on("fontsize",function(b){g.handleFontSize(b)});g.refs.topbar=r;var t=new c({root:g.root});t.on("mobilemenu",function(b){g.handleMobileMenu(b)});g.refs.menu=t;return{c:function(){f=document.createElement("div");r._fragment.c();d=document.createTextNode("\n  ");t._fragment.c();
b=document.createTextNode("\n  ");l=document.createElement("div");e=document.createElement("div");e.innerHTML="Disclaimer:\x3cbr\x3eThis documentation is a work in progress. It isn't ready and shouldn't be shared with outsiders until the removal of this message. If you want to help build it, please \x3ca href\x3d\"https://github.com/peercoin/docs#peercoin-official-documentation-repository\"\x3eclick here\x3c/a\x3e.";h=document.createTextNode("\n    ");m=document.createElement("div");n=document.createTextNode("\n    ");
p=document.createElement("div");this.h()},h:function(){e.className="warn";m.className="menu-swipper";p.className=q="doc-container font-"+k.fontSize;l.className="body";f.className="MainComp"},m:function(a,c){a.insertBefore(f,c);r._mount(f,null);f.appendChild(d);t._mount(f,null);f.appendChild(b);f.appendChild(l);l.appendChild(e);l.appendChild(h);l.appendChild(m);l.appendChild(n);l.appendChild(p);p.innerHTML=k.documentationHTML;g.refs.docContainer=p},p:function(b,a){b.documentationHTML&&(p.innerHTML=
a.documentationHTML);b.fontSize&&q!==(q="doc-container font-"+a.fontSize)&&(p.className=q)},u:function(){p.innerHTML="";f.parentNode.removeChild(f)},d:function(){r.destroy(!1);g.refs.topbar===r&&(g.refs.topbar=null);t.destroy(!1);g.refs.menu===t&&(g.refs.menu=null);g.refs.docContainer===p&&(g.refs.docContainer=null)}}}function p(a){B(this,a);this.refs={};this._state=n({fontSize:2,documentation:"",documentationHTML:""},a.data);var c=this;a.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=
[]);this._fragment=z(this,this._state);this.root._oncreate.push(function(){c.registerDocumentation();c.fire("update",{changed:{fontSize:1,documentationHTML:1},current:c._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,m(this._beforecreate),m(this._oncreate),m(this._aftercreate),this._lock=!1)}function B(a,c){a._handlers=Object.create(null);a._bind=c._bind;a.options=c;a.root=c.root||a;a.store=a.root.store||c.store}function n(a,c){for(var g in c)a[g]=c[g];return a}
function m(a){for(;a&&a.length;)a.shift()()}function v(a){this.destroy=r;this.fire("destroy");this.set=this.get=r;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function r(){}var e=q("../herodotus-settings.js"),c=q("./menu.component"),a=q("./topbar.component"),t=q("marked"),f=q("@fdaciuk/ajax");q("hammerjs");var y=q("prismjs");e=e&&e.__esModule?e["default"]:e;c=c&&c.__esModule?c["default"]:c;a=a&&a.__esModule?a["default"]:a;t=t&&t.__esModule?t["default"]:t;f=f&&f.__esModule?
f["default"]:f;y=y&&y.__esModule?y["default"]:y;n(p.prototype,{destroy:v,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var g=0;g<a.length;g+=1){var d=a[g];d.__calling||(d.__calling=!0,d.call(this,c),d.__calling=!1)}},observe:function(a,c,f){var d=c.bind(this);f&&!1===f.init||d(this.get()[a],void 0);return this.on(f&&f.defer?"update":"state",function(b){b.changed[a]&&d(b.current[a],b.previous&&b.previous[a])})},on:function(a,
c){if("teardown"===a)return this.on("destroy",c);var g=this._handlers[a]||(this._handlers[a]=[]);g.push(c);return{cancel:function(){var a=g.indexOf(c);~a&&g.splice(a,1)}}},set:function(a){this._set(n({},a));this.root._lock||(this.root._lock=!0,m(this.root._beforecreate),m(this.root._oncreate),m(this.root._aftercreate),this.root._lock=!1)},teardown:v,_set:function(a){var c=this._state,g={},d=!1,b;for(b in a)this._differs(a[b],c[b])&&(g[b]=d=!0);d&&(this._state=n(n({},c),a),this._recompute(g,this._state),
this._bind&&this._bind(g,this._state),this._fragment&&(this.fire("state",{changed:g,current:this._state,previous:c}),this._fragment.p(g,this._state),this.fire("update",{changed:g,current:this._state,previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});n(p.prototype,{getParentId:function(a){return"end"===a?null:
a.id&&-1<["H1","H2"].indexOf(a.tagName)?{id:a.id,title:a.textContent}:this.getParentId(a.previousElementSibling||"end")},generateSearchList:function(){var a=this,c=[];[].concat($jscomp.arrayFromIterable(document.querySelector(".doc-container").children)).forEach(function(f){var d=a.getParentId(f);d&&c.push({id:d.id,title:d.title,content:f.textContent})});return c},handleFontSize:function(a){switch(a.action){case "INCREASE":this.increaseFont();break;case "DECREASE":this.decreaseFont()}},handleMobileMenu:function(a){switch(a.action){case "TOGGLE":this.refs.topbar.set({isMenuOpen:this.refs.menu.toggle()});
break;case "CLOSE":this.refs.menu.close();this.refs.topbar.set({isMenuOpen:!1});break;case "OPEN":this.refs.menu.open(),this.refs.topbar.set({isMenuOpen:!0})}},increaseFont:function(){var a=this.get("fontSize");4<=a||this.set({fontSize:a+1})},decreaseFont:function(){var a=this.get("fontSize");1>=a||this.set({fontSize:a-1})},registerDocumentation:function(){var a=this;var c=e.allow_remote_documentation?e.remote_documentation_url:"documentation.md";f().get(c).then(function(c,d){a.set({documentation:c,
documentationHTML:t(c)});a.refs.menu.startMenu(a.generateMenu());a.refs.topbar.refs.searchlist.set({searchList:a.generateSearchList()});a.responsiveTables();y.highlightAll()})},responsiveTables:function(){Array.from(document.querySelectorAll(".doc-container table")).forEach(function(a){var c=document.createElement("div");c.classList.add("responsive-table");a.parentElement.insertBefore(c,a);c.appendChild(a)})},generateMenu:function(){var a=[],c=[],f;this.refs.docContainer.querySelectorAll("h1, h2").forEach(function(d){c.push({type:d.nodeName.toLowerCase(),
label:d.textContent,id:d.id});"h1"===d.nodeName.toLowerCase()?(a.push({type:d.nodeName.toLowerCase(),label:d.textContent,id:d.id}),f=a[a.length-1],f.children=[]):"h2"===d.nodeName.toLowerCase()&&f.children.push({type:d.nodeName.toLowerCase(),label:d.textContent,id:d.id})});return{menuItems:a,menuItemsFlat:c}}});p.prototype._recompute=r;x.exports=p});require.register("components/menu.component.svelte",function(h,q,x){function z(a,b){(new w(a)).on("swipeleft",b)}function p(){var a=this;window.onhashchange=
function(){a.scrollToURLMenu()}}function B(c,b){function d(b){c.onAppScroll(this.scrollY)}function f(b){c.fire("mobilemenu",{action:"CLOSE"})}var e,g,k,h,m,p,w,r,q,y;window.addEventListener("scroll",d);for(var v=b.menuItems,x=[],B=0;B<v.length;B+=1)x[B]=n(c,a(a({},b),{each_value:v,item:v[B],item_index:B}));return{c:function(){e=document.createElement("div");g=document.createElement("div");h=document.createTextNode("\n  ");m=document.createElement("div");p=document.createElement("img");w=document.createTextNode("\n    ");
r=document.createElement("ul");for(var b=0;b<x.length;b+=1)x[b].c();this.h()},h:function(){g.addEventListener("click",f,!1);g.className=k="MenuComp--overlay "+(b.isOpen?"active":"");p.src="img/logo.svg";p.alt="Peercoin University";p.className="logo";r.className="menu";q=z.call(c,m,function(b){c.fire("mobilemenu",{action:"CLOSE"})});m.className=y="MenuComp "+(b.isOpen?"open":"")},m:function(b,a){b.insertBefore(e,a);e.appendChild(g);c.refs.overlay=g;e.appendChild(h);e.appendChild(m);m.appendChild(p);
m.appendChild(w);m.appendChild(r);for(b=0;b<x.length;b+=1)x[b].m(r,null);c.refs.menu=m},p:function(b,d){b.isOpen&&k!==(k="MenuComp--overlay "+(d.isOpen?"active":""))&&(g.className=k);var f=d.menuItems;if(b.menuItems){for(var l=0;l<f.length;l+=1){var e=a(a({},d),{each_value:f,item:f[l],item_index:l});x[l]?x[l].p(b,e):(x[l]=n(c,e),x[l].c(),x[l].m(r,null))}for(;l<x.length;l+=1)x[l].u(),x[l].d();x.length=f.length}b.isOpen&&y!==(y="MenuComp "+(d.isOpen?"open":""))&&(m.className=y)},u:function(){e.parentNode.removeChild(e);
for(var b=0;b<x.length;b+=1)x[b].u()},d:function(){window.removeEventListener("scroll",d);g.removeEventListener("click",f,!1);c.refs.overlay===g&&(c.refs.overlay=null);t(x);q[q.destroy?"destroy":"teardown"]();c.refs.menu===m&&(c.refs.menu=null)}}}function n(a,b){var c=b.item,d,f,e=c.label,g,k,h,m,p,n=0<c.children.length&&v(a,b);return{c:function(){d=document.createElement("li");f=document.createElement("a");g=document.createTextNode(e);h=document.createTextNode("\n            ");n&&n.c();this.h()},
h:function(){f.addEventListener("click",r,!1);f.href=k="#"+c.id;f._svelte={component:a,each_value:b.each_value,item_index:b.item_index};d.id=m="menu-"+c.id;d.className=p=c.type},m:function(b,a){b.insertBefore(d,a);d.appendChild(f);f.appendChild(g);d.appendChild(h);n&&n.m(d,null)},p:function(b,l){c=l.item;b.menuItems&&e!==(e=c.label)&&(g.data=e);b.menuItems&&k!==(k="#"+c.id)&&(f.href=k);f._svelte.each_value=l.each_value;f._svelte.item_index=l.item_index;0<c.children.length?n?n.p(b,l):(n=v(a,l),n.c(),
n.m(d,null)):n&&(n.u(),n.d(),n=null);b.menuItems&&m!==(m="menu-"+c.id)&&(d.id=m);b.menuItems&&p!==(p=c.type)&&(d.className=p)},u:function(){d.parentNode.removeChild(d);n&&n.u()},d:function(){f.removeEventListener("click",r,!1);n&&n.d()}}}function m(a,b){var c=b.subitem,d,f,g=c.label,k,h,m,n;return{c:function(){d=document.createElement("li");f=document.createElement("a");k=document.createTextNode(g);this.h()},h:function(){f.addEventListener("click",e,!1);f.href=h="#"+c.id;f._svelte={component:a,each_value_1:b.each_value_1,
subitem_index:b.subitem_index};d.id=m="menu-"+c.id;d.className=n=c.type},m:function(b,a){b.insertBefore(d,a);d.appendChild(f);f.appendChild(k)},p:function(b,a){c=a.subitem;b.menuItems&&g!==(g=c.label)&&(k.data=g);b.menuItems&&h!==(h="#"+c.id)&&(f.href=h);f._svelte.each_value_1=a.each_value_1;f._svelte.subitem_index=a.subitem_index;b.menuItems&&m!==(m="menu-"+c.id)&&(d.id=m);b.menuItems&&n!==(n=c.type)&&(d.className=n)},u:function(){d.parentNode.removeChild(d)},d:function(){f.removeEventListener("click",
e,!1)}}}function v(c,b){for(var d=b.item,f,e=d.children,g=[],k=0;k<e.length;k+=1)g[k]=m(c,a(a({},b),{each_value_1:e,subitem:e[k],subitem_index:k}));return{c:function(){f=document.createElement("ul");for(var b=0;b<g.length;b+=1)g[b].c();this.h()},h:function(){f.className="subsection"},m:function(b,a){b.insertBefore(f,a);for(b=0;b<g.length;b+=1)g[b].m(f,null)},p:function(b,e){d=e.item;var l=d.children;if(b.menuItems){for(var k=0;k<l.length;k+=1){var h=a(a({},e),{each_value_1:l,subitem:l[k],subitem_index:k});
g[k]?g[k].p(b,h):(g[k]=m(c,h),g[k].c(),g[k].m(f,null))}for(;k<g.length;k+=1)g[k].u(),g[k].d();g.length=l.length}},u:function(){f.parentNode.removeChild(f);for(var b=0;b<g.length;b+=1)g[b].u()},d:function(){t(g)}}}function r(a){this._svelte.component.scrollToItem(this._svelte.each_value[this._svelte.item_index],a)}function e(a){this._svelte.component.scrollToItem(this._svelte.each_value_1[this._svelte.subitem_index],a)}function c(c){f(this,c);this.refs={};this._state=a({menuItems:[],menuItemsFlat:[],
isOpen:!1,prevY:0},c.data);var b=this;c.root||(this._oncreate=[]);this._fragment=B(this,this._state);this.root._oncreate.push(function(){p.call(b);b.fire("update",{changed:{isOpen:1,menuItems:1},current:b._state})});c.target&&(this._fragment.c(),this._mount(c.target,c.anchor),y(this._oncreate))}function a(a,b){for(var c in b)a[c]=b[c];return a}function t(a){for(var b=0;b<a.length;b+=1)a[b]&&a[b].d()}function f(a,b){a._handlers=Object.create(null);a._bind=b._bind;a.options=b;a.root=b.root||a;a.store=
a.root.store||b.store}function y(a){for(;a&&a.length;)a.shift()()}function g(a){this.destroy=k;this.fire("destroy");this.set=this.get=k;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function k(){}var w=q("hammerjs");w=w&&w.__esModule?w["default"]:w;a(c.prototype,{destroy:g,get:function(a){return a?this._state[a]:this._state},fire:function(a,b){if(a=a in this._handlers&&this._handlers[a].slice())for(var c=0;c<a.length;c+=1){var d=a[c];d.__calling||(d.__calling=!0,d.call(this,
b),d.__calling=!1)}},observe:function(a,b,c){var d=b.bind(this);c&&!1===c.init||d(this.get()[a],void 0);return this.on(c&&c.defer?"update":"state",function(b){b.changed[a]&&d(b.current[a],b.previous&&b.previous[a])})},on:function(a,b){if("teardown"===a)return this.on("destroy",b);var c=this._handlers[a]||(this._handlers[a]=[]);c.push(b);return{cancel:function(){var a=c.indexOf(b);~a&&c.splice(a,1)}}},set:function(c){this._set(a({},c));this.root._lock||(this.root._lock=!0,y(this.root._beforecreate),
y(this.root._oncreate),y(this.root._aftercreate),this.root._lock=!1)},teardown:g,_set:function(c){var b=this._state,d={},f=!1,g;for(g in c)this._differs(c[g],b[g])&&(d[g]=f=!0);f&&(this._state=a(a({},b),c),this._recompute(d,this._state),this._bind&&this._bind(d,this._state),this._fragment&&(this.fire("state",{changed:d,current:this._state,previous:b}),this._fragment.p(d,this._state),this.fire("update",{changed:d,current:this._state,previous:b})))},_mount:function(a,b){this._fragment[this._fragment.i?
"i":"m"](a,b||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,b){return a!=a?b==b:a!==b||a&&"object"===typeof a||"function"===typeof a}});a(c.prototype,{onAppScroll:function(a){a=this.get("menuItemsFlat");a=$jscomp.makeIterator(a.entries());for(var b=a.next();!b.done;b=a.next()){b=$jscomp.makeIterator(b.value);b.next();b=b.next().value;var c=document.getElementById(b.id),d=c.getBoundingClientRect().top;c=c.getBoundingClientRect().bottom;if(0<=d&&c<=window.innerHeight){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu li.active"))).map(function(a){return a.classList.remove("active")});
a=document.getElementById("menu-"+b.id);a.classList.add("active");b=a.parentNode;b.classList.contains("subsection")&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),b.classList.add("show"));0<a.querySelectorAll(".subsection").length&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),a.querySelector(".subsection").classList.add("show"));
break}}},startMenu:function(a){var b=this;this.set(a);setTimeout(function(){b.scrollToURLMenu()},10)},scrollTop:function(){window.scrollTo(0,0);this.close()},scrollToURLMenu:function(){var a=window.location.hash.substr(2),b=this.get("menuItemsFlat").filter(function(b){return b.id===a});0<b.length?(b=document.getElementById(b[0].id),b=window.scrollY+b.getBoundingClientRect().top-70,window.scrollTo(0,b)):window.scrollTo(0,1)},toggle:function(){this.set({isOpen:!this.refs.menu.isOpen});return this.refs.menu.isOpen},
close:function(){this.set({isOpen:!1})},open:function(){this.set({isOpen:!0})},scrollToItem:function(a,b){b&&b.preventDefault();window.location.hash="/"+a.id;this.get("menuItemsFlat");a=window.scrollY+document.getElementById(a.id).getBoundingClientRect().top-70;window.scrollTo(0,a);this.fire("mobilemenu",{action:"CLOSE"})}});c.prototype._recompute=k;x.exports=c});require.register("components/searchlist.component.svelte",function(h,q,x){function z(){var a=this;this.observe("searchList",function(c){a.fuse=
a.setFuse(c)})}function p(a,c){function d(b){a.toggleSearch()}function b(b){a.closeSearch()}function f(b){a.handleSearch(b)}function g(b){a.isClosable(b)}var k,h,p,w,r,q,t,y,v,x,z,B,A,C=1<c.filteredList.length&&n(a,c),J=1>c.filteredList.length&&m(a,c);return{c:function(){k=document.createElement("div");h=document.createElement("div");p=e("svg");w=e("use");r=document.createTextNode("\n  \n  ");q=document.createElement("div");y=document.createTextNode("\n\n  ");v=document.createElement("div");x=document.createElement("input");
z=document.createTextNode("\n    ");C&&C.c();B=document.createTextNode("\n\n    ");J&&J.c();this.h()},h:function(){w.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-search.svg#icon");w.setAttribute("preserveAspectRatio","xMidYMid");p.addEventListener("click",d,!1);p.setAttribute("class","svg-icon");p.setAttribute("xmlns","http://www.w3.org/2000/svg");p.setAttribute("role","img");p.setAttribute("viewBox","0 0 15 15");h.className="btn btn-svg";q.addEventListener("click",b,!1);q.className=
t="SearchListComp--overlay "+(c.isOpen?"active":"");x.addEventListener("input",f,!1);x.addEventListener("keydown",g,!1);x.setAttribute("type","text");x.className="filter-input";x.placeholder="Search here...";v.className=A="search-popup "+(c.isOpen?"open":"");k.className="SearchListComp"},m:function(b,c){b.insertBefore(k,c);k.appendChild(h);h.appendChild(p);p.appendChild(w);k.appendChild(r);k.appendChild(q);k.appendChild(y);k.appendChild(v);v.appendChild(x);a.refs.input=x;v.appendChild(z);C&&C.m(v,
null);v.appendChild(B);J&&J.m(v,null)},p:function(b,c){b.isOpen&&t!==(t="SearchListComp--overlay "+(c.isOpen?"active":""))&&(q.className=t);1<c.filteredList.length?C?C.p(b,c):(C=n(a,c),C.c(),C.m(v,B)):C&&(C.u(),C.d(),C=null);1>c.filteredList.length?J||(J=m(a,c),J.c(),J.m(v,null)):J&&(J.u(),J.d(),J=null);b.isOpen&&A!==(A="search-popup "+(c.isOpen?"open":""))&&(v.className=A)},u:function(){k.parentNode.removeChild(k);C&&C.u();J&&J.u()},d:function(){p.removeEventListener("click",d,!1);q.removeEventListener("click",
b,!1);x.removeEventListener("input",f,!1);x.removeEventListener("keydown",g,!1);a.refs.input===x&&(a.refs.input=null);C&&C.d();J&&J.d()}}}function B(a,c){var d=c.item,b,f,g,e=d.item.title,k,h,m,n=d.item.content.substr(0,100),p,w,q;return{c:function(){b=document.createElement("li");f=document.createElement("a");g=document.createElement("div");k=document.createTextNode(e);h=document.createTextNode("\n          ");m=document.createElement("div");p=document.createTextNode(n);w=document.createTextNode("...");
this.h()},h:function(){g.className="section-title";m.className="section-text";f.addEventListener("click",v,!1);f.href=q="#/"+d.item.id;f._svelte={component:a};b.className="item"},m:function(a,c){a.insertBefore(b,c);b.appendChild(f);f.appendChild(g);g.appendChild(k);f.appendChild(h);f.appendChild(m);m.appendChild(p);m.appendChild(w)},p:function(a,b){d=b.item;a.filteredList&&e!==(e=d.item.title)&&(k.data=e);a.filteredList&&n!==(n=d.item.content.substr(0,100))&&(p.data=n);a.filteredList&&q!==(q="#/"+
d.item.id)&&(f.href=q)},u:function(){b.parentNode.removeChild(b)},d:function(){f.removeEventListener("click",v,!1)}}}function n(a,f){for(var d,b=f.filteredList,g=[],e=0;e<b.length;e+=1)g[e]=B(a,c(c({},f),{each_value:b,item:b[e],item_index:e}));return{c:function(){d=document.createElement("ul");for(var a=0;a<g.length;a+=1)g[a].c();this.h()},h:function(){d.className="filtered-list"},m:function(a,b){a.insertBefore(d,b);for(a=0;a<g.length;a+=1)g[a].m(d,null)},p:function(b,f){var e=f.filteredList;if(b.filteredList){for(var k=
0;k<e.length;k+=1){var h=c(c({},f),{each_value:e,item:e[k],item_index:k});g[k]?g[k].p(b,h):(g[k]=B(a,h),g[k].c(),g[k].m(d,null))}for(;k<g.length;k+=1)g[k].u(),g[k].d();g.length=e.length}},u:function(){d.parentNode.removeChild(d);for(var a=0;a<g.length;a+=1)g[a].u()},d:function(){for(var a=0;a<g.length;a+=1)g[a]&&g[a].d()}}}function m(c,f){var d;return{c:function(){d=document.createElement("h2");d.textContent="No matches found.";this.h()},h:function(){d.className="empty-message"},m:function(a,c){a.insertBefore(d,
c)},u:function(){d.parentNode.removeChild(d)},d:a}}function v(a){this._svelte.component.closeSearch()}function r(a){t(this,a);this.refs={};this._state=c({searchList:[],filteredList:[],fuse:null,isOpen:!1},a.data);var g=this;a.root||(this._oncreate=[]);this._fragment=p(this,this._state);this.root._oncreate.push(function(){z.call(g);g.fire("update",{changed:{isOpen:1,filteredList:1},current:g._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),f(this._oncreate))}function e(a){return document.createElementNS("http://www.w3.org/2000/svg",
a)}function c(a,c){for(var d in c)a[d]=c[d];return a}function a(){}function t(a,c){a._handlers=Object.create(null);a._bind=c._bind;a.options=c;a.root=c.root||a;a.store=a.root.store||c.store}function f(a){for(;a&&a.length;)a.shift()()}function y(c){this.destroy=a;this.fire("destroy");this.set=this.get=a;!1!==c&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var g=q("fuse.js");g=g&&g.__esModule?g["default"]:g;c(r.prototype,{destroy:y,get:function(a){return a?this._state[a]:this._state},
fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var d=0;d<a.length;d+=1){var b=a[d];b.__calling||(b.__calling=!0,b.call(this,c),b.__calling=!1)}},observe:function(a,c,d){var b=c.bind(this);d&&!1===d.init||b(this.get()[a],void 0);return this.on(d&&d.defer?"update":"state",function(c){c.changed[a]&&b(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var d=this._handlers[a]||(this._handlers[a]=[]);d.push(c);return{cancel:function(){var a=
d.indexOf(c);~a&&d.splice(a,1)}}},set:function(a){this._set(c({},a));this.root._lock||(this.root._lock=!0,f(this.root._beforecreate),f(this.root._oncreate),f(this.root._aftercreate),this.root._lock=!1)},teardown:y,_set:function(a){var f=this._state,d={},b=!1,g;for(g in a)this._differs(a[g],f[g])&&(d[g]=b=!0);b&&(this._state=c(c({},f),a),this._recompute(d,this._state),this._bind&&this._bind(d,this._state),this._fragment&&(this.fire("state",{changed:d,current:this._state,previous:f}),this._fragment.p(d,
this._state),this.fire("update",{changed:d,current:this._state,previous:f})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});c(r.prototype,{openSearch:function(){this.set({isOpen:!0});this.refs.input.focus()},closeSearch:function(){this.set({isOpen:!1})},toggleSearch:function(){this.get("isOpen")?this.closeSearch():this.openSearch()},
isClosable:function(a){27===a.keyCode&&this.closeSearch()},setFuse:function(a){1>a.length||this.set({fuse:new g(a,{shouldSort:!0,findAllMatches:!0,includeMatches:!0,threshold:.3,location:0,distance:1E4,maxPatternLength:32,minMatchCharLength:3,keys:["content"]})})},handleSearch:function(a){3<a.target.value.length?this.set({filteredList:this.get("fuse").search(a.target.value)}):this.set({filteredList:[]});console.log(this.get("filteredList"))}});r.prototype._recompute=a;x.exports=r});require.register("components/topbar.component.svelte",
function(h,q,x){function z(c,e){function f(a){c.fire("mobilemenu",{action:"TOGGLE"})}function k(a){c.scrollTop()}var h,d,b,l,n,q,r,t,y,v,x,z,D=e.settings.allow_font_size_control&&p(c,e),C=new a({root:c.root});c.refs.searchlist=C;var A=e.settings.allow_topbar_link&&B(c,e);return{c:function(){h=document.createElement("div");d=document.createElement("div");b=m("svg");l=m("use");q=document.createTextNode("\n\n    ");r=document.createElement("div");r.innerHTML='\x3cimg src\x3d"img/logo.svg" alt\x3d"Peercoin Docs"\x3e';
t=document.createTextNode("\n\n    ");D&&D.c();y=document.createTextNode("\n\n    ");v=document.createElement("hr");x=document.createTextNode("\n\n    ");C._fragment.c();z=document.createTextNode("\n\n    ");A&&A.c();this.h()},h:function(){l.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-menu-open.svg#icon");l.setAttribute("preserveAspectRatio","xMidYMid");var a=n="svg-icon "+(e.isMenuOpen?"off":"");b.setAttribute("class",a);b.setAttribute("xmlns","http://www.w3.org/2000/svg");
b.setAttribute("role","img");b.setAttribute("viewBox","0 0 40 28");d.addEventListener("click",f,!1);d.className="menu-button";r.addEventListener("click",k,!1);r.className="logo";h.className="TopbarComp"},m:function(a,c){a.insertBefore(h,c);h.appendChild(d);d.appendChild(b);b.appendChild(l);h.appendChild(q);h.appendChild(r);h.appendChild(t);D&&D.m(h,null);h.appendChild(y);h.appendChild(v);h.appendChild(x);C._mount(h,null);h.appendChild(z);A&&A.m(h,null)},p:function(a,d){a.isMenuOpen&&n!==(n="svg-icon "+
(d.isMenuOpen?"off":""))&&b.setAttribute("class",n);d.settings.allow_font_size_control?D||(D=p(c,d),D.c(),D.m(h,y)):D&&(D.u(),D.d(),D=null);d.settings.allow_topbar_link?A?A.p(a,d):(A=B(c,d),A.c(),A.m(h,null)):A&&(A.u(),A.d(),A=null)},u:function(){h.parentNode.removeChild(h);D&&D.u();A&&A.u()},d:function(){d.removeEventListener("click",f,!1);r.removeEventListener("click",k,!1);D&&D.d();C.destroy(!1);c.refs.searchlist===C&&(c.refs.searchlist=null);A&&A.d()}}}function p(a,c){function f(b){a.fire("fontsize",
{action:"DECREASE"})}function e(b){a.fire("fontsize",{action:"INCREASE"})}var h,d,b,l;return{c:function(){h=document.createElement("div");d=document.createElement("div");d.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-minus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';b=document.createTextNode("\n      ");l=document.createElement("div");l.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-plus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';
this.h()},h:function(){d.addEventListener("click",f,!1);d.className="btn btn-svg v-center";l.addEventListener("click",e,!1);l.className="btn btn-svg v-center";h.className="btn-group"},m:function(a,c){a.insertBefore(h,c);h.appendChild(d);h.appendChild(b);h.appendChild(l)},u:function(){h.parentNode.removeChild(h)},d:function(){d.removeEventListener("click",f,!1);l.removeEventListener("click",e,!1)}}}function B(a,c){var f,e,h,d=c.settings.topbar_link_label,b,l;return{c:function(){f=document.createElement("a");
e=document.createElement("span");e.textContent="Contribute to";h=document.createElement("b");b=document.createTextNode(d);this.h()},h:function(){f.href=l=c.settings.topbar_link_url;f.className="btn btn-last-link"},m:function(a,c){a.insertBefore(f,c);f.appendChild(e);f.appendChild(h);h.appendChild(b)},p:function(a,c){a.settings&&d!==(d=c.settings.topbar_link_label)&&(b.data=d);a.settings&&l!==(l=c.settings.topbar_link_url)&&(f.href=l)},u:function(){f.parentNode.removeChild(f)},d:v}}function n(a){this._handlers=
Object.create(null);this._bind=a._bind;this.options=a;this.root=a.root||this;this.store=this.root.store||a.store;this.refs={};this._state=r({settings:t},a.data);a.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=[]);this._fragment=z(this,this._state);a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,e(this._beforecreate),e(this._oncreate),e(this._aftercreate),this._lock=!1)}function m(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function v(){}
function r(a,c){for(var f in c)a[f]=c[f];return a}function e(a){for(;a&&a.length;)a.shift()()}function c(a){this.destroy=v;this.fire("destroy");this.set=this.get=v;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var a=q("./searchlist.component"),t=q("../herodotus-settings.js");a=a&&a.__esModule?a["default"]:a;t=t&&t.__esModule?t["default"]:t;r(n.prototype,{destroy:c,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var f=
0;f<a.length;f+=1){var e=a[f];e.__calling||(e.__calling=!0,e.call(this,c),e.__calling=!1)}},observe:function(a,c,e){var f=c.bind(this);e&&!1===e.init||f(this.get()[a],void 0);return this.on(e&&e.defer?"update":"state",function(c){c.changed[a]&&f(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var f=this._handlers[a]||(this._handlers[a]=[]);f.push(c);return{cancel:function(){var a=f.indexOf(c);~a&&f.splice(a,1)}}},set:function(a){this._set(r({},
a));this.root._lock||(this.root._lock=!0,e(this.root._beforecreate),e(this.root._oncreate),e(this.root._aftercreate),this.root._lock=!1)},teardown:c,_set:function(a){var c=this._state,f={},e=!1,h;for(h in a)this._differs(a[h],c[h])&&(f[h]=e=!0);e&&(this._state=r(r({},c),a),this._recompute(f,this._state),this._bind&&this._bind(f,this._state),this._fragment&&(this.fire("state",{changed:f,current:this._state,previous:c}),this._fragment.p(f,this._state),this.fire("update",{changed:f,current:this._state,
previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});n.prototype._recompute=v;x.exports=n});require.register("herodotus-settings.js",function(h,q,x){Object.defineProperty(h,"__esModule",{value:!0});h.default={documentation_name:"Peercoin University",allow_topbar_link:!0,topbar_link_label:"Peercoin University",topbar_link_url:"https://github.com/peercoin/PeercoinUniversity",
allow_font_size_control:!0,allow_remote_documentation:!1,remote_documentation_url:""}});require.register("initialize.js",function(h,q,x){var z=(h=q("./components/main.component"))&&h.__esModule?h:{default:h};document.addEventListener("DOMContentLoaded",function(){window.mainComponent=new z.default({target:document.querySelector("main")})})});require.alias("@fdaciuk/ajax/dist/ajax.min.js","@fdaciuk/ajax");require.alias("fuse.js/dist/fuse.js","fuse.js");require.alias("hammerjs/hammer.js","hammerjs");
require.alias("marked/lib/marked.js","marked");require.alias("prismjs/prism.js","prismjs");require.register("___globals___",function(h,q,x){})})();require("___globals___");require("initialize");